### ISSUE TITLE
已经在docker部署和运行成功，但访问8090输出404错误，如何解决？

### ISSUE THREAD

**Issue by heavensea** [TeamWiseFlow/wiseflow#100]
已经按照作者文字说明一步步完成了配置
也设置的admin用户名的邮件和密码
也重新启动了container
命令行显示程序也已经运行了，也在pb后台加了tag和sites内容

终端显示内容如下：
[+] Running 1/0
 ✔ Container wiseflow-core-1  Created                                                                                                                                                    0.0s
Attaching to core-1
core-1  | 2024/09/17 15:55:03 Server started at http://0.0.0.0:8090
core-1  | ├─ REST API: http://0.0.0.0:8090/api/
core-1  | └─ Admin UI: http://0.0.0.0:8090/_/
core-1  | INFO:     Will watch for changes in these directories: ['/app']
core-1  | INFO:     Uvicorn running on http://0.0.0.0:8077 (Press CTRL+C to quit)
core-1  | INFO:     Started reloader process [1] using StatReload
core-1  | 2024-09-17 15:55:04.354 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://127.0.0.1:8090
core-1  | 2024-09-17 15:55:04.774 | INFO     | utils.pb_api:__init__:22 - pocketbase ready authenticated as admin - chenghao@gmail.com
core-1  | 2024-09-17 15:55:04.796 | INFO     | __main__:schedule_pipeline:19 - task execute loop 1
core-1  | 2024-09-17 15:55:04.797 | INFO     | __main__:process_site:11 - applying https://finance.sina.com.cn/7x24/
core-1  | 2024-09-17 15:55:04.797 | DEBUG    | insights:pipeline:34 - start processing https://finance.sina.com.cn/7x24
core-1  | 2024-09-17 15:55:04.820 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://127.0.0.1:8090
core-1  | 2024-09-17 15:55:04.925 | INFO     | scrapers.general_crawler:general_crawler:98 - can not reach
core-1  | Redirect response '301 Moved Permanently' for url 'https://finance.sina.com.cn/7x24'
core-1  | Redirect location: '/7x24/'
core-1  | For more information check: https://httpstatuses.com/301
core-1  | waiting 1min
core-1  | 2024-09-17 15:55:05.182 | INFO     | utils.pb_api:__init__:22 - pocketbase ready authenticated as admin - xxxxxxx@gmail.com
core-1  | INFO:     Started server process [26]
core-1  | INFO:     Waiting for application startup.
core-1  | INFO:     Application startup complete.

但访问http://127.0.0.1:8090/还是显示如下：
{"code":404,"message":"Not Found.","data":{}}

该如何解决？

**Comment by heavensea** [comment]
在pb管理后台，logs中，显示访问错误
![1726588987721](https://github.com/user-attachments/assets/aa30d115-781e-4825-928f-21df720409f7)

**Comment by bigbrother666sh** [comment]
信源https://finance.sina.com.cn/7x24 封禁了你的 IP，建议写专有信源解析器

**Comment by heavensea** [comment]
> 信源https://finance.sina.com.cn/7x24 封禁了你的 IP，建议写专有信源解析器

我换了别的信源也是一样的。，这个{"code":404,"message":"Not Found.","data":{}}应该跟信源无关吧？

![image](https://github.com/user-attachments/assets/08143908-eb8c-4536-9a0e-25554b869368)

**Comment by heavensea** [comment]
请问，如果工作正常，访问ip:8090后，应该显示什么界面？是不是不应访问ip:8090啊，就是访问ip:8090/_/就是正常运行了？

**Comment by fariskiteen** [comment]
我跟你一样  搞了一下午了  我还真以为就我一个如此

**Comment by fariskiteen** [comment]
解决的话踢我一下谢谢

**Comment by bigbrother666sh** [comment]
What should be displayed after accessing ip:8090 if the work is normal? Shouldn't ip:8090 be accessed, or is accessing ip:8090/_/ a sign of normal operation?

没错，所有的抓取结果都会在 ip:8090/_/  下面的 insight 页面中

**Comment by fangyu6** [comment]
请问，设置sites和tags后，为什么insights并没有显示抓取内容

**Comment by bigbrother666sh** [comment]
> 请问，设置sites和tags后，为什么insights并没有显示抓取内容

贴一下logs

**Comment by fangyu6** [comment]
![image](https://github.com/user-attachments/assets/5a5fd737-78f4-4b67-a0a4-dbc62419bf07)

**Comment by pphanwang** [comment]
![image](https://github.com/user-attachments/assets/048a06f5-a6bf-4a8d-bd90-8d2f9c4d6f5b)
我到这样，直接没有下文，不知道怎么搞

**Comment by pphanwang** [comment]
{
  "id": "bjrph2d7rh9bfhw",
  "created": "2024-10-09 00:55:09.315Z",
  "updated": "2024-10-09 00:55:09.315Z",
  "data": {
    "auth": "guest",
    "details": "code=404, message=Not Found",
    "error": "Not Found.",
    "execTime": 0.2672,
    "method": "GET",
    "referer": "",
    "remoteIp": "127.0.0.1",
    "status": 404,
    "type": "request",
    "url": "/",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0",
    "userIp": "127.0.0.1"
  },
  "message": "GET /",
  "level": 8
}

**Comment by pphanwang** [comment]
![image](https://github.com/user-attachments/assets/f1dc2f34-3310-49a0-b3c1-6d93f223288e)

**Comment by fangyu6** [comment]
![7a2a7aa36b7ea840193f2ef1487ab5b](https://github.com/user-attachments/assets/19bd114e-8961-4c9e-9444-951710e12aed)
@bigbrother666sh 请问一下 密码和用户已经确定和pb的保持一致，为什么情报分析的网页还是登录不了

**Comment by bigbrother666sh** [comment]
127.0.0.1:8090/_/ 么？

**Comment by fangyu6** [comment]
不是 是:5173/login

**Comment by bigbrother666sh** [comment]
你用的是代码仓里面的 dashboard？
