### ISSUE TITLE
建议出一个完整教程～

### ISSUE THREAD

**Issue by allen-studio** [TeamWiseFlow/wiseflow#103]
花了这么多时间做了这么好的一个产品，但是没有任何介绍详细使用的，搜遍全网只在bilibili找到2个介绍的很快的视频，还有零星几篇文章，完全没搞懂，酒香也怕巷子深啊

**Comment by bigbrother666sh** [comment]
#48 https://gist.github.com/Rodert/dec3f413c498f742da53cdbb767d8220

**Comment by allen-studio** [comment]
> #48 https://gist.github.com/Rodert/dec3f413c498f742da53cdbb767d8220

谢谢，我的意思是产品使用的介绍视频～用docker部署和运行没什么问题的，我已经借助AI都搞完了

**Comment by bigbrother666sh** [comment]
那不是已经很好了，再好的教程也赶不上动手实践。反之教程无论怎么写都还是会有人提出各种问题的

**Comment by ezrealliu** [comment]
可以借鉴下我的部署过程（稍微详细一点点）: https://juejin.cn/post/7428119275473879052 ，不过用的不是 docker
