### ISSUE TITLE
docker compose up Run has been mistaken as in the picture below

### ISSUE THREAD

**Issue by gjxwwww8888** [TeamWiseFlow/wiseflow#105]
![image](https://github.com/user-attachments/assets/9efcaa16-201b-4c8a-89d1-e8759906304d)

**Comment by bigbrother666sh** [comment]
没看懂……

**Comment by gjxwwww8888** [comment]
> 没看懂……
![image](https://github.com/user-attachments/assets/92b396ef-1fda-4192-878f-984816b2662e)
这个是我设置的.env文件
![image](https://github.com/user-attachments/assets/8be1e18f-b95a-4e16-8ca0-4c04ef85ebcf)

但是运行结果还是会报下面的错误
![image](https://github.com/user-attachments/assets/f8016c1d-0312-4500-abf3-a78c8bc7ab70)
这个是什么原因没搞明白？是否可以提供帮助谢谢

**Comment by bigbrother666sh** [comment]
你动过代码了吧？重新拉一下代码仓再试试

**Comment by zx1n2580** [comment]
docker_entrypoint.sh: line 2: $'\r': command not found
2024-10-11 13:44:23 core-1  | docker_entrypoint.sh: line 3: $'\r': command not found

**Comment by bigbrother666sh** [comment]
> docker_entrypoint.sh: line 2: $'\r': command not found 2024-10-11 13:44:23 core-1 | docker_entrypoint.sh: line 3: $'\r': command not found

重新拉一下代码
