### ISSUE TITLE
docker 日志报错是什么原因

### ISSUE THREAD

**Issue by zx1n2580** [TeamWiseFlow/wiseflow#107]
![屏幕截图 2024-10-10 174424](https://github.com/user-attachments/assets/e6007879-82fd-4626-907d-f534336bd250)

**Comment by zx1n2580** [comment]
![屏幕截图 2024-10-10 175712](https://github.com/user-attachments/assets/b17cb834-689c-464e-897c-7d021f10a661)
还有这些接口失败的

**Comment by bigbrother666sh** [comment]
你没正确设定 pb 的 email 和密码吧，仔细看看 README

**Comment by zx1n2580** [comment]
但是我已经登上pb的ui了呀
![屏幕截图 2024-10-11 102443](https://github.com/user-attachments/assets/97f636f4-2e69-49bb-a1ad-63bc60291a86)

**Comment by gjxwwww8888** [comment]
我也是遇到类似的问题，未能找到解决方法
![image](https://github.com/user-attachments/assets/298c9042-cf3e-4dc2-adc5-77022d35dc92)

**Comment by gjxwwww8888** [comment]
![image](https://github.com/user-attachments/assets/59a2c682-0846-42cb-8538-e5ba0af889f1)

**Comment by zx1n2580** [comment]
你解决了吗

**Comment by gjxwwww8888** [comment]
还是没有找到解决方案

**Comment by zx1n2580** [comment]
在你的.env配置上加上export PB_API_BASE="http://127.0.0.1:8090/"试试
