### ISSUE TITLE
运行过程报错超时

### ISSUE THREAD

**Issue by gjxwwww8888** [TeamWiseFlow/wiseflow#108]
![image](https://github.com/user-attachments/assets/40a50ebc-14a1-41fd-afae-f3bc5f781d70)

**Comment by zx1n2580** [comment]
pb数据库没配置对

**Comment by gjxwwww8888** [comment]
应该如何操作呢？我尝试了好多遍一直没成功

**Comment by zx1n2580** [comment]
export LLM_API_KEY=""
export LLM_API_BASE="https://api.siliconflow.cn/v1" #for local model services or calling non-OpenAI services with openai_wrapper
#trongly recommended to use the following model provided by siliconflow (consider both effect and price)
export GET_INFO_MODEL="THUDM/glm-4-9b-chat" ##
export REWRITE_MODEL="Qwen/Qwen2-72B-Instruct"
export HTML_PARSE_MODEL="Qwen/Qwen2-72B-Instruct"
export PROJECT_DIR="work"
export PB_API_AUTH="test@example.com|1234567890"
export PB_API_BASE="http://127.0.0.1:8090/" ##only use if your pb not run on 127.0.0.1:8090
export WS_LOG="verbose" #for detail log info. If not need, just delete this item.
export VOLC_KEY="1|1"填上自己的apikey 试试这个env文件呢

**Comment by gjxwwww8888** [comment]
这个我已经设置过了，下面是我之前设置的
![image](https://github.com/user-attachments/assets/9f6203be-fc5b-43f5-8616-1f9158ee33e7)

**Comment by zx1n2580** [comment]
我的是加上export PB_API_BASE="http://127.0.0.1:8090/"就好了

**Comment by gjxwwww8888** [comment]
![image](https://github.com/user-attachments/assets/0402c4f1-a10b-4f6e-a8d9-d08fffaef4f9)
改完现在就报这个错

**Comment by zx1n2580** [comment]
那不知道了

**Comment by bigbrother666sh** [comment]
本地运行，且默认在8090端口运行 pocketbase serve时无需填入 PB_API_BASE， 我觉得你可能是 PB 的用户名密码填错了
