### ISSUE TITLE
在users里面添加了用户，但是登录不上去，而且没有数据隔离

### ISSUE THREAD

**Issue by hxujal** [TeamWiseFlow/wiseflow#109]

**Comment by bigbrother666sh** [comment]
可以通过每个 collection 的 setting 实现简单的数据隔离，具体请参考 pocketbase 文档

**Comment by z1054136399** [comment]
> 可以通过每个 collection 的 setting 实现简单的数据隔离，具体请参考 pocketbase 文档

可以详细说一下改哪部分代码吗？
顺便问一下最近有什么其它的更新计划吗？

**Comment by bigbrother666sh** [comment]
不用改代码，是打开 pocketbase 的dashboard 做设置

接下来会是两个方向，一个是 RAG 结合，发展可在线学习的组织内知识智能体，另一个就是 wiseflow 要能够继承更多类型的网页信息提取器

**Comment by hxujal** [comment]
> 不用改代码，是打开 pocketbase 的dashboard 做设置
> 
> 接下来会是两个方向，一个是 RAG 结合，发展可在线学习的组织内知识智能体，另一个就是 wiseflow 要能够继承更多类型的网页信息提取器

大佬方便截个图吗，没找到
