### ISSUE TITLE
国内环境部署时候一些小问题，建议优化

### ISSUE THREAD

**Issue by riddle911** [TeamWiseFlow/wiseflow#11]
1. 部署慢或失败
拉取python slim 3.10时，由于网络问题，会拉取失败，设置阿里云源也会失败。

解决：自己找了个源，手动拉取

2.执行dockerfile过慢
dockerfile中
```
RUN apt-get update && \
    apt-get install -yq tzdata build-essential unzip && \
    apt-get clean
```
这一步，由于debian源过慢，基本会失败。

解决（？）：切换源为阿里云（没有完全解决，敲这行字时候还在执行)

**Comment by death4444** [comment]
虽然慢，但是最后你部署成功了没？
我编译都能过，容器也有了，就是跑不起来。
你慢的问题，可以搜索一下，Cloudflare加速方案

**Comment by riddle911** [comment]
> 虽然慢，但是最后你部署成功了没？ 我编译都能过，容器也有了，就是跑不起来。 你慢的问题，可以搜索一下，Cloudflare加速方案

docker部署成功。慢的问题，就是全部换国内源就能解决。

**Comment by linuxyn** [comment]
FROM python:3.10-slim

# 设置为中国国内源
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# Using douban pipy mirror
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ -U pip 
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN apt-get update && \
    apt-get install -yq tzdata build-essential unzip && \
    apt-get clean

WORKDIR /app

COPY core/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY core .

# download and unzip PocketBase
# ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
ADD pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
# for arm device
# ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_arm64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /app/pb/

EXPOSE 8090
EXPOSE 8077

CMD tail -f /dev/null



#  建议使用这个Dockerfile,即把pip和Debian的源都切换为阿里云的源，提前把pocketbase的包下载下来就很快了

**Comment by linuxyn** [comment]
> FROM python:3.10-slim
> 
> # 设置为中国国内源
> RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
> 
> # Using douban pipy mirror
> RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ -U pip RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/
> 
> RUN apt-get update && apt-get install -yq tzdata build-essential unzip && apt-get clean
> 
> WORKDIR /app
> 
> COPY core/requirements.txt requirements.txt RUN pip install --no-cache-dir -r requirements.txt
> 
> COPY core .
> 
> # download and unzip PocketBase
> # ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
> ADD pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
> 
> # for arm device
> # ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_arm64.zip /tmp/pb.zip
> RUN unzip /tmp/pb.zip -d /app/pb/
> 
> EXPOSE 8090 EXPOSE 8077
> 
> CMD tail -f /dev/null
> 
> # 建议使用这个Dockerfile,即把pip和Debian的源都切换为阿里云的源，提前把pocketbase的包下载下来就很快了

**Comment by linuxyn** [comment]
```
# 设置为中国国内源
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# Using douban pipy mirror
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ -U pip 
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN apt-get update && \
    apt-get install -yq tzdata build-essential unzip && \
    apt-get clean

WORKDIR /app

COPY core/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY core .

# download and unzip PocketBase
# ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
ADD pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
# for arm device
# ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_arm64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /app/pb/

EXPOSE 8090
EXPOSE 8077

CMD tail -f /dev/null
```


# 建议使用这个Dockerfile,即把pip和Debian的源都切换为阿里云的源，提前把pocketbase的包下载下来就很快了

**Comment by linuxyn** [comment]
```
FROM python:3.10-slim

RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# Using douban pipy mirror
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ -U pip 
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN apt-get update && \
    apt-get install -yq tzdata build-essential unzip && \
    apt-get clean

WORKDIR /app

COPY core/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY core .

# download and unzip PocketBase
# ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
ADD pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
# for arm device
# ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.13/pocketbase_0.22.13_linux_arm64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /app/pb/

EXPOSE 8090
EXPOSE 8077

CMD tail -f /dev/null
```

建议使用这个Dockerfile,即把pip和Debian的源都切换为国内的源，提前把pocketbase的包下载下来，再次部署就很快了

**Comment by spikezh** [comment]
apt update 之前 需要http 替换给https， 否则报没有签名。

**Comment by pinsily** [comment]
```
FROM python:3.10-slim

RUN rm -rf /etc/apt/sources.list.d/*
RUN rm -rf /etc/apt/sources.list

# 创建新的 sources.list 文件，仅使用 USTC 镜像
RUN echo "deb http://mirrors.ustc.edu.cn/debian bookworm main contrib non-free non-free-firmware\n\
deb http://mirrors.ustc.edu.cn/debian bookworm-updates main contrib non-free non-free-firmware\n\
deb http://mirrors.ustc.edu.cn/debian-security bookworm-security main contrib non-free non-free-firmware" > /etc/apt/sources.list

# 使用阿里云 PyPI 镜像
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ -U pip
RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN apt-get update && \
    apt-get install -yq tzdata build-essential unzip && \
    apt-get clean

WORKDIR /app
COPY core/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY core .

# 添加并解压 PocketBase
ADD pocketbase_0.22.13_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /app/pb/

EXPOSE 8090
EXPOSE 8077

CMD tail -f /dev/null
```

可以启动的dockerfile
