### ISSUE TITLE
添加历史信息获取模式的支持

### ISSUE THREAD

**Issue by blackwhite084** [TeamWiseFlow/wiseflow#111]
现在的模式主要是发掘实时新信息，但可能较多人会有需求希望去发掘历史性的信息，如在某个时间段；

**Comment by bigbrother666sh** [comment]
更改 core/insights/__init__.py 这里的 expiration_days即可

**Comment by blackwhite084** [comment]
> 更改 core/insights/**init**.py 这里的 expiration_days即可

那然后关于链接到底是解析成文章还是链接列表这个功能有问题，不能很好的识别到底是文字还是链接列表，感觉应该是需要同时识别是否有文章以及链接列表的，然后如果加上历史信息模式的话，可能还会涉及到爬取的深度

**Comment by bigbrother666sh** [comment]
> > 更改 core/insights/**init**.py 这里的 expiration_days即可
> 
> 那然后关于链接到底是解析成文章还是链接列表这个功能有问题，不能很好的识别到底是文字还是链接列表，感觉应该是需要同时识别是否有文章以及链接列表的，然后如果加上历史信息模式的话，可能还会涉及到爬取的深度

这个问题确实目前版本不是特别理想（目前版本是简单的判断页面里面包含多少个跟站点主域名一致的 url 来判断是 list 还是 article），正在思考更优化的方案。
