### ISSUE TITLE
Windows环境下部署wiseflow，如何运行backend.py和tasks.py

### ISSUE THREAD

**Issue by SummerChris** [TeamWiseFlow/wiseflow#112]
如题，已安装说明下载项目，虚拟环境用python -m venv .venv命令创建并激活，也做了Windows环境变量配置，pocketbase.exe已运行，但执行tasks.py报错，见下图。请教在Windows环境下，如何运行项目？
![图片](https://github.com/user-attachments/assets/a53ec751-c59b-47cc-b274-f771c5f2cfc9)
![图片](https://github.com/user-attachments/assets/a3dc2577-831c-4cfd-b8a2-ecb63e2fbbe6)

**Comment by bigbrother666sh** [comment]
没有配置.env，而且按照你这种运行方式，可能程序也找不到.env ……
请严格按照 readme 进行操作

**Comment by ezrealliu** [comment]
将 git 的sh 加到 系统环境中；先开启 pb （需要直接走到 pb 目录下，第一次执行按 readme.md 中操作 ）；然后开启另一个 命令行；按 readme.md 中文档说的  把 core/scripts 中的 *.sh 复制到 core 中，进入到 core 目录， 创建 conda wiseflow 环境，安装所需要的包，使用 sh start_backend.sh；同样的操作 start_tasks.sh 都可以跑起来

**Comment by ezrealliu** [comment]
可以借鉴下我的部署过程: https://juejin.cn/post/7428119275473879052
