### ISSUE TITLE
使用docker 运行docker compose up报错

### ISSUE THREAD

**Issue by SummerChris** [TeamWiseFlow/wiseflow#113]
linux和docker都是正在学习中，按步骤操作，提示一个错误，请问怎么解决。操作系统是centos7，自带python2.7.5，安装了python3.10.4，镜像源已更换成国内的。
![image](https://github.com/user-attachments/assets/ff2aad7a-7811-4bb1-a6c7-ef0669e2f325)
![image](https://github.com/user-attachments/assets/f02a22de-65e2-4e85-96d5-6a95874643c9)

**Comment by bigbrother666sh** [comment]
这是网络问题，不是我这边的问题……

不过你也可以试试下面的，但各自网络情况不同，仅供参考
{
  "registry-mirrors": ["https://registry.docker-cn.com","https://nrbewqda.mirror.aliyuncs.com","https://dmmxhzvq.mirror.aliyuncs.com"]
  }
