### ISSUE TITLE
insights的获取和爬取文章取消耦合

### ISSUE THREAD

**Issue by blackwhite084** [TeamWiseFlow/wiseflow#115]
有的时候可能会有自己的文章爬取方式，并自己写入到这个数据库。
有的时候可能新增加了tag，并希望重新消化历史文章中的insights。

**Comment by bigbrother666sh** [comment]
可以把自定义网页提取器放在 core/scrapers 里面，然后 在__init__.py 里面注册下对应的站点主域名就可以了
