### ISSUE TITLE
insights里面的content仍然有很多英文的

### ISSUE THREAD

**Issue by RomaCredit** [TeamWiseFlow/wiseflow#116]
首先，群主辛苦，开源万岁！
其次，如果能有一个简单的采集和聚合逻辑介绍就好了，比如articles和insights的简单生成逻辑。
最后，为啥insights里面有很多条目还是英文的呢？我理解群主定义insights是想把文章里面的核心内容提炼出来，方便阅读，但是为啥很多没有经过翻译？

想改代码，又怕重复造轮子，群主弄个微信群，把有兴趣的拉进去，一起商量下怎么改呗。有些改动，可能群主自己整几行代码就搞定了，其他人费劲重复浪费时间。

再次，群主万岁！

**Comment by bigbrother666sh** [comment]
感谢关注，这些都是通过大模型本身的能力实现的，你如果想让它直接生成中文可以改 prompt 啊（core/insights/__init__.py)
