### ISSUE TITLE
语言以及时区设置

### ISSUE THREAD

**Issue by live-in-the-moment** [TeamWiseFlow/wiseflow#119]
使用conda 环境运行，该如何设置修改 或者 使用 LANG=zh_CN.UTF-8 -e LC_CTYPE=zh_CN.UTF-8 ？ 配置在start_pd.sh start_tacks.sh都没有效果；

**Comment by bigbrother666sh** [comment]
docker run -e LANG=zh_CN.UTF-8 -e LC_CTYPE=zh_CN.UTF-8 your_image

**Comment by live-in-the-moment** [comment]
@bigbrother666sh 在不使用docker 部署启动的情况下呢？

**Comment by bigbrother666sh** [comment]
那不就是跟着你系统走的么

**Comment by bigbrother666sh** [comment]
数据库都是显示世界协调时，也就是UTC（比中国时间晚8小时），你鼠标停留在时间上，就显示本地时间了
