### ISSUE TITLE
为什么insights是空的？如何配置？

### ISSUE THREAD

**Issue by linopluss** [TeamWiseFlow/wiseflow#122]
已经抓取到了文章，也配置的ChatGPT的API， 为什么是insight是空的？

.env配置见下图
<img width="765" alt="image" src="https://github.com/user-attachments/assets/2ef5f277-a8b7-4392-8a5d-8007e04047ba">

**Comment by bigbrother666sh** [comment]
也能是 tags那边没配置，建议仔细阅读 readme
之后如有更多问题，请上传详细 log
