### ISSUE TITLE
抓取到的内容为cookies提醒，正常的文章抓取不到。

### ISSUE THREAD

**Issue by linopluss** [TeamWiseFlow/wiseflow#123]
问题：抓取不到正常的文章，只抓取到了cookies提醒。

content 例子1
[from tcl] This site uses cookies to analyse site traffic, improve your experience and personalize ads or other contents. By clicking Accept or continuing to browse the site, you are agree to our use of cookies. See our Cookies Policy here.
Learn more

content 例子2
[from chiq] Our website uses cookies to enhance your browsing experience and to better understand how you use our site. By clicking 'Accept', you consent to the use of cookies, or by clicking
'Reject'
, you refuse the use of cookies.

content 例子3
[from haier] Thank you!
You have successfully subscribed to our newsletter and will receive a
 confirmation email shortly. Our newsletter brings you an exclusive preview
 of our latest products and promotions, plus design inspiration straight to
 your inbox.

tags配置
<img width="905" alt="image" src="https://github.com/user-attachments/assets/908c8919-dc8d-4e9d-a618-4356ea0d3340">

url配置
<img width="886" alt="image" src="https://github.com/user-attachments/assets/19f05b2f-600e-4c6e-a8f1-2ab779ae8e45">

**Comment by bigbrother666sh** [comment]
针对这些要写专有网页提取器了，开源代码仓配备的通用网页提取器，仅支持一般常见的新闻网站，微信公众号文章

**Comment by bigbrother666sh** [comment]
可以再试试看 V0.3.5版本，如果还是不能很好的抓取，请在  #136 中跟帖 url
