### ISSUE TITLE
设置了tag和site，但是任务运行时间超短，而且没有任何收集到的信息

### ISSUE THREAD

**Issue by bryan-ym** [TeamWiseFlow/wiseflow#125]
按照说明进行的docker安装，启动都正常，如下图。但是搜不到任何信息，观察发现一次task运行的时间只有0.001秒，求大神解惑
![image](https://github.com/user-attachments/assets/84ca91c1-bf64-4246-a82e-0a75173cd27b)
tag设置：
![image](https://github.com/user-attachments/assets/9eafb33b-af6b-4ff3-97d2-889ed6635d5c)
site设置：
![image](https://github.com/user-attachments/assets/4b60e7d1-cf24-444b-98a7-d2cc3e5420be)

**Comment by bigbrother666sh** [comment]
tag 的内容是需要的信息点描述，不是具体的问题（这不是 ai 搜索），不过这不是最致命的问题。
主要是你 sites 里面给的 url 都是单一文章，也就是只有一篇文章，那当然很快了，同时也自然大概率提取不到有用信息了……
要给站点，也就是文章列表页面

**Comment by bryan-ym** [comment]
> tag 的内容是需要的信息点描述，不是具体的问题（这不是 ai 搜索），不过这不是最致命的问题。 主要是你 sites 里面给的 url 都是单一文章，也就是只有一篇文章，那当然很快了，同时也自然大概率提取不到有用信息了…… 要给站点，也就是文章列表页面

多谢回复，另外，我在siliconflow的api key使用计费环节，也没有被使用的记录，上面问题中我忘记说了。所以我觉得wiseflow似乎没有调用siliconflow

**Comment by bryan-ym** [comment]
还有个可能的原因，安装过程中要用到外部的源比较慢，所以我修改了docker和pip的源，源代码还是从GitHub克隆的，这些会影响代码运行吗？

**Comment by bigbrother666sh** [comment]
只要源是可靠的，理论上不会
