### ISSUE TITLE
如何配置多个LLM_API_BASE

### ISSUE THREAD

**Issue by aideshizhe** [TeamWiseFlow/wiseflow#126]
由于不同的模型效果不一样，
比如我要分别使用glm4和gpt4o-mini的话，由不同的模型服务商提供，两个不同的LLM_API_BASE和LLM_API_KEY，是否支持，该怎么进行配置
请教大佬！

**Comment by bigbrother666sh** [comment]
这个要改下代码了，不过并不复杂
