### ISSUE TITLE
为什么只抓取了列表页，未抓取到文章详情页？

### ISSUE THREAD

**Issue by linopluss** [TeamWiseFlow/wiseflow#128]
site设置：
<img width="584" alt="image" src="https://github.com/user-attachments/assets/706b7b93-bbca-438d-a907-8ef7024aa7f1">

tags设置：
<img width="574" alt="image" src="https://github.com/user-attachments/assets/35f44b75-ed23-4894-acf4-adec3ea59577">

只抓取到了列表页
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/d7360037-bf06-4eb7-a502-ab60cac5bf18">

**Comment by bigbrother666sh** [comment]
可以再试试看 V0.3.5版本，有问题的话，欢迎在 #136 中提出你的 url
