### ISSUE TITLE
是api调用的问题吗？为什么抓不到数据？求教大佬！

### ISSUE THREAD

**Issue by qinheyi** [TeamWiseFlow/wiseflow#129]
![微信截图_20241120210651](https://github.com/user-attachments/assets/bbd27153-515e-4028-bdfa-31a0c97ae2dc)
![微信截图_20241120210857](https://github.com/user-attachments/assets/91a370b9-812b-4906-beed-83e111bd8f48)
![微信截图_20241120210907](https://github.com/user-attachments/assets/5810d8d6-db8c-4840-b454-e5f7720a5dfd)
![微信截图_20241120210717](https://github.com/user-attachments/assets/6829119c-2eed-4e37-beba-557c66f7e946)
![微信截图_20241120210921](https://github.com/user-attachments/assets/76a32bea-894a-47e0-b060-7684002538b6)
.env都配置好了，tag也写了，site也写了。项目部署在阿里云，用宝塔docker拉的，有大佬知道怎么回事吗？

**Comment by bigbrother666sh** [comment]
放一下项目运行的 log。
另外现在 siliconflow 已经放出 qwen2.5系列了，可以尝试使用：Qwen/Qwen2.5-7B-Instruct 替代所有模型

**Comment by qinheyi** [comment]
![捕获](https://github.com/user-attachments/assets/b1d30e9b-c56a-49e4-b904-7ad3e661e407)
作者好！.env已经改成qwen2.5，重启后还是失败，容器运营日志是这里

**Comment by bigbrother666sh** [comment]
没设置 llm_api_base 和 llm_api_key

**Comment by qinheyi** [comment]
好像是宝塔面板docker的问题，重新拉了一遍docker，信息都带入了，谢谢
