### ISSUE TITLE
bash: docker_entrypoint.sh: No such file or directory

### ISSUE THREAD

**Issue by oliwenfly** [TeamWiseFlow/wiseflow#132]
![局部截取_20241122_203506](https://github.com/user-attachments/assets/0139c1db-045c-4fd7-a243-e428876c8d5c)

重装了一次镜像，也是这样，但是我在core文件夹里能找到这个sh文件，请问怎么解决

**Comment by bigbrother666sh** [comment]
删除现有镜像，重新拉代码，重新 build docker
