### ISSUE TITLE
项目部署了但是一直没insights

### ISSUE THREAD

**Issue by SuqingLiu** [TeamWiseFlow/wiseflow#133]
用的是openai 的key
export GET_INFO_MODEL="gpt-4o-mini-2024-07-18" ##
export REWRITE_MODEL="gpt-4o-mini-2024-07-18"
export HTML_PARSE_MODEL="gpt-4o-mini-2024-07-18"

<img width="918" alt="image" src="https://github.com/user-attachments/assets/22746db2-465c-4460-adc7-087fc049312e">

没有设置sites，因为想试试全网搜效果怎么样。
但是到现在都是空的，也不确定是多久发一次请求

感谢帮助

**Comment by SuqingLiu** [comment]
log 显示开了pocketbase后就不往下走了

**Comment by bigbrother666sh** [comment]
必须指定 site
