### ISSUE TITLE
运行pocketbase serve提示错误   migrate up命令怎么用 这个怎么配置pocketbase serve  

### ISSUE THREAD

**Issue by Joneshan907** [TeamWiseFlow/wiseflow#134]
Failed to execute main.pb.js:
 - TypeError: Object has no member 'requireRecordAuth' at <eval>:33:26(6)
Error: Failed to apply migration 1712449900_created_article_translation.js: ReferenceError: Dao is not defined at <eval>:49:13(83)

**Comment by bigbrother666sh** [comment]
dashboard 部分是参考，仅供有代码能力的同学自己二次开发使用。正常用户不必关注这里
