### ISSUE TITLE
浏览器引擎抓取不到数据

### ISSUE THREAD

**Issue by tang51678** [TeamWiseFlow/wiseflow#135]
大师傅为什么，配置数据源和关键词，页重启了了
百度，不等浏览器引擎，为什么抓取不到 ，需要自己改代码吗，还是什么。

**Comment by wwz-wyze** [comment]
尝试重启一下项目试试，重启浏览器引擎应该没什么作用

**Comment by tang51678** [comment]
那就是我想问一下，他这个首先这个项目他能不能就是说检索这个浏览器的这种这个引擎？
然后我看了代码好像就是二次检索结果的时候默认的是搜狗，这个应该也可以改自己，是吧？












敢不敢
***@***.***

欢迎关注＂开心网安＂
15351410762



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月28日(周四) 中午11:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TeamWiseFlow/wiseflow] 浏览器引擎抓取不到数据 (Issue #135)




 
尝试重启一下项目试试，重启浏览器引擎应该没什么作用

**Comment by bigbrother666sh** [comment]
dashboard 部分是参考，目前并没有实际使用。

**Comment by tang51678** [comment]
好的&nbsp; 谢谢




tangkaixing
***@***.***

欢迎关注＂开心网安＂
15351410762




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TeamWiseFlow/wiseflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TeamWiseFlow/wiseflow] 浏览器引擎抓取不到数据 (Issue #135)





 
dashboard 部分是参考，目前并没有实际使用。
