### ISSUE TITLE
部署pocketbase 失败，win11环境，源码部署

### ISSUE THREAD

**Issue by bigshipai** [TeamWiseFlow/wiseflow#137]
(wiseflow) PS E:\codespace\22\wiseflow\core\pb> pocketbase migrate up
Failed to execute main.pb.js:
 - TypeError: Object has no member 'requireRecordAuth' at <eval>:33:26(6)
Error: Failed to apply migration 1712449900_created_article_translation.js: ReferenceError: Dao is not defined at <eval>:49:13(83)

**Comment by bigbrother666sh** [comment]
源码部署目前是存在这个问题，正在解决

**Comment by lishaozheng** [comment]
我也遇到同样的问题
Failed to execute main.pb.js:
 - TypeError: Object has no member 'requireRecordAuth' at <eval>:33:26(6)
Error: Failed to apply migration 1712449900_created_article_translation.js: ReferenceError: Dao is not defined at <eval>:49:13(83)

**Comment by Fan-Yu-Feng** [comment]
./pocketbase migrate up # for first run

Failed to execute main.pb.js:
 - TypeError: Object has no member 'requireRecordAuth' at <eval>:33:26(6)
Error: Failed to apply migration 1712449900_created_article_translation.js: ReferenceError: Dao is not defined at <eval>:49:13(83)
+1

**Comment by bigbrother666sh** [comment]
V0.3.2 版本会升级适配最新版本的 pocketbase，预计周末发布

**Comment by bigbrother666sh** [comment]
可以试试看最新版本 https://github.com/TeamWiseFlow/wiseflow/tree/dev

**Comment by bigbrother666sh** [comment]
V0.3.5版本已经发布 
#145

**Comment by Fan-Yu-Feng** [comment]
> 可以试试看最新版本 https://github.com/TeamWiseFlow/wiseflow/tree/dev

试了下没问题了
