### ISSUE TITLE
想问下，/api/admins这个接口是在哪个版本的pocketbase生效的？

### ISSUE THREAD

**Issue by Charles-ux-bit** [TeamWiseFlow/wiseflow#139]
<img width="492" alt="image" src="https://github.com/user-attachments/assets/ef51a412-00ad-4c4a-9de0-bba9d5abe9c1">

执行start_tasks.sh和start_backend.sh时都会报restful API 404，base_crud_path是/api/admins，这个方法在已安装的pocketbase中看不到呀，pocketbase的登录链接是：

<img width="535" alt="image" src="https://github.com/user-attachments/assets/07afbdd4-4010-40f1-8512-0a1251c89da3">

求解答，谢谢

**Comment by bigbrother666sh** [comment]
你安装 pocketbase的python SDK了么？
直接用这个 SDK 啊 
pip install pocketbase

**Comment by Charles-ux-bit** [comment]
> 你安装 pocketbase的python SDK了么？ 直接用这个 SDK 啊 pip install pocketbase

我是安装了的，不过代码中用的是http请求呀，不是调用的pocketbase的python sdk接口。我能确认一下，以下来源是正确的么：

https://garden.1900.live/00-inbox/wiseflow-readme_cn-md-at-master-%C2%B7-teamwiseflow-wiseflow

git clone https://github.com/TeamWiseFlow/wiseflow.git
cd wiseflow


在这个code中，auth-with-passwd确实报404，没有这个method

**Comment by bigbrother666sh** [comment]
…… 你都来 github 提 issue 了，不会看下 github 的代码仓么……

**Comment by ZhiXiao-Lin** [comment]
我这里也是404，看了源码好像  `admin_data = self.client.admins.auth_with_password(email, password)` 这一行的API被废弃了
```
core-1  | 2024-12-07 04:13:37.957 | DEBUG    | utils.pb_api:__init__:14 - initializing pocketbase client: http://127.0.0.1:8090
core-1  | Process SpawnProcess-1:
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 21, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 90, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:404
core-1  |
core-1  | During handling of the above exception, another exception occurred:
core-1  |
```

**Comment by ZhiXiao-Lin** [comment]
![image](https://github.com/user-attachments/assets/a890002d-81b2-41cf-a60e-b0bc1430a691)

**Comment by ZhiXiao-Lin** [comment]
解决方案

**Comment by bigbrother666sh** [comment]
也可以试试看 dev 分支最新版本，适配了最新版本的 pocketbase，同时换了更加强大专业的爬虫框架

**Comment by Charles-ux-bit** [comment]
切换成dev分支后，正常认证了，但连接pocketbase后的get_list时报404/400错误，不知道pocketbase具体扮演什么角色，是要做哪些初始化么？代码位置在这里：
![image](https://github.com/user-attachments/assets/0c7531b8-4ca3-4b98-80ab-f1f401ecf137)

这四个入参的值打印出来是：tags activated=True None True

**Comment by bigbrother666sh** [comment]
更新最新的 V0.3.5 吧，记得完全删除旧代码，包括 pb_data
