### ISSUE TITLE
请问有人遇到过ClientResponseError404吗？

### ISSUE THREAD

**Issue by tititico** [TeamWiseFlow/wiseflow#140]
环境是Ubuntu 24.04.1 LTS. 已经注册了admin，也已经修改了.env文件。
错误信息：
~/wiseflow$ docker compose up
[+] Running 1/0
 ✔ Container wiseflow-core-1  Created                                                                              0.0s 
Attaching to core-1
core-1  | 2024/12/06 05:40:39 Server started at http://0.0.0.0:8090
core-1  | ├─ REST API: http://0.0.0.0:8090/api/
core-1  | └─ Admin UI: http://0.0.0.0:8090/_/
core-1  | INFO:     Will watch for changes in these directories: ['/app']
core-1  | INFO:     Uvicorn running on http://0.0.0.0:8077 (Press CTRL+C to quit)
core-1  | INFO:     Started reloader process [1] using StatReload
core-1  | 2024-12-06 05:40:40.641 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://127.0.0.1:8090
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 20, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 90, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:404
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/app/tasks.py", line 2, in <module>
core-1  |     from insights import pipeline, pb, logger
core-1  |   File "/app/insights/__init__.py", line 5, in <module>
core-1  |     from .get_info import get_info, pb, project_dir, logger, info_rewrite
core-1  |   File "/app/insights/get_info.py", line 26, in <module>
core-1  |     pb = PbTalker(logger)
core-1  |   File "/app/utils/pb_api.py", line 24, in __init__
core-1  |     user_data = self.client.collection("users").auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 218, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 116, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.errors.ClientResponseError: Response error. Status code:400
请问可能是什么问题呢？

**Comment by tititico** [comment]
已解决

**Comment by ZhiXiao-Lin** [comment]
> 已解决

怎么解决的？

**Comment by tititico** [comment]
> > 已解决
> 
> 怎么解决的？

参考了issue#144，修改requirements.txt里的pocketbase为0.12.1版本后就可以了
