### ISSUE TITLE
使用docker 运行docker compose up报错   python:3.10-slim     EOF 

### ISSUE THREAD

**Issue by lishaozheng** [TeamWiseFlow/wiseflow#143]
(wiseflow) H:\LiProject\wiseflow>docker compose up
[+] Running 1/1
 ! core Warning pull access denied for wiseflow, repository does not exist or may require 'docker...              20.5s
[+] Building 27.0s (2/2) FINISHED                                                                  docker:desktop-linux
 => [core internal] load build definition from Dockerfile                                                          0.0s
 => => transferring dockerfile: 678B                                                                               0.0s
 => ERROR [core internal] load metadata for docker.io/library/python:3.10-slim                                    27.0s
------
 > [core internal] load metadata for docker.io/library/python:3.10-slim:
------
failed to solve: python:3.10-slim: failed to resolve source metadata for docker.io/library/python:3.10-slim: failed to do request: Head "https://registry.docker-cn.com/v2/library/python/manifests/3.10-slim?ns=docker.io": EOF

(wiseflow) H:\LiProject\wiseflow>

![image](https://github.com/user-attachments/assets/ed2d56bf-b390-42b6-b836-3d9899293378)

**Comment by bigbrother666sh** [comment]
{
 "registry-mirrors": ["https://registry.docker-cn.com","https://registry.dockermirror.com", "https://docker.nju.edu.cn", "http://hub-mirror.c.163.com", "https://mirror.baidubce.com", "https://ccr.ccs.tencentyun.com","https://dockerproxy.com", "http://mirrors.ustc.edu.cn/"]
}

**Comment by bigbrother666sh** [comment]
多弄几个，不行就考虑科学上网
