### ISSUE TITLE
wind10  运行 (wiseflow) H:\LiProject\wiseflow\core\pb>pocketbase serve  报错

### ISSUE THREAD

**Issue by lishaozheng** [TeamWiseFlow/wiseflow#144]
版本 ： pocketbase_0.22.13_windows_amd64
(wiseflow) H:\LiProject\wiseflow\core\pb>pocketbase serve
Error: Failed to apply migration 1673167670_multi_match_migrate.go: SQL logic error: no such column: schema (1)

**Comment by bigbrother666sh** [comment]
可以了，可以试试看 https://github.com/TeamWiseFlow/wiseflow/tree/dev
