### ISSUE TITLE
python 部署问题     python tasks.py 和   报错  utils.pb_api:read:41 -  pocketbase get list failed: Response error. Status code:403

### ISSUE THREAD

**Issue by lishaozheng** [TeamWiseFlow/wiseflow#147]
问一下这个403怎么解决呢， 然后查到是   Only superusers can perform this action.      但是我用的就是超级用户

![image](https://github.com/user-attachments/assets/6c1ece23-ccfc-491a-81cd-39861ed8a99f)

![image](https://github.com/user-attachments/assets/dfe3dac6-f71a-4081-add4-a2602424fc30)

 
![企业微信截图_1733822107471](https://github.com/user-attachments/assets/1cd33257-c5ba-48ab-ae30-3642bc9a5a9b)

**Comment by bigbrother666sh** [comment]
你试试看把密码改成长一点的，10位

**Comment by lishaozheng** [comment]
好的，还是一样的问题 😭
invalid email|password found, will handle with not auth, make sure you have set the collection ru
le by anyone

![image](https://github.com/user-attachments/assets/bf3bdcf3-7dbe-4761-a495-cc3cfc550cf6)

**Comment by bigbrother666sh** [comment]
你要去 pb 那里该用户名密码，改好后再更新到.env

**Comment by lishaozheng** [comment]
没看到pd里面哪里能改，我是在这里改的
![image](https://github.com/user-attachments/assets/d9e0652b-4293-4ab2-9ccb-5c6f42482fc0)

要改用户名密码的话是这个的数据库里面吗
![image](https://github.com/user-attachments/assets/5efc65c4-0ee6-4dda-86a5-4a2f0d50d7fd)

**Comment by lishaozheng** [comment]
您好，可以说详细一点吗   pd那里的用户名密码是在哪个文件里

当我在  pb_api里默认了账户密码后  就是 pocketbase ready authenticated as user - 1363435208@qq.com   这样了
![image](https://github.com/user-attachments/assets/dd826603-37f2-4830-a220-aa9487c4b1f4)
但是还有是 403 的报错  在这里
![image](https://github.com/user-attachments/assets/40e0fad2-a763-4b55-9b8f-4ba878f61be0)

**Comment by lishaozheng** [comment]
> 我也出现了这个问题，请问如何解决的？

主要就是账户密码的问题，
1、检测是不是超级用户的账户密码  
2、在代码里面，看pd登入的是不是 超级用户

**Comment by bigbrother666sh** [comment]
@lishaozheng @liuchang012463 可以升级到 V0.3.6（重新拉取代码，删除 pb/pb_data)，
