### ISSUE TITLE
bash: cd: core: 没有那个文件或目录 ERROR: Could not open requirements file: [Errno 2] 没有那个文件或目录: 'requirement.txt'

### ISSUE THREAD

**Issue by flyricci** [TeamWiseFlow/wiseflow#15]
conda create -n wiseflow python=3.10
conda activate wiseflow
cd core
pip install -r requirement.txt

bash: cd: core: 没有那个文件或目录
ERROR: Could not open requirements file: [Errno 2] 没有那个文件或目录: 'requirement.txt'

**Comment by wwz223** [comment]
@flyricci  #10
