### ISSUE TITLE
如何修改监听的端口？

### ISSUE THREAD

**Issue by ipv6ok** [TeamWiseFlow/wiseflow#155]
http://127.0.0.1:8090  默认这个，但是部署在服务器上的话，不方便。建议直接整到配置文件中。

**Comment by bigbrother666sh** [comment]
pb 启动的时候可以指定端口（pocketbase docs上有介绍）
然后在.env 里面配置下即可

**Comment by ipv6ok** [comment]
感谢，可以了。
