### ISSUE TITLE
按照README.md的要求配置好环境，设置好focus_points和sites后，执行了多轮的循环没有任何infos存储在pocketbase

### ISSUE THREAD

**Issue by calmyun** [TeamWiseFlow/wiseflow#159]
![1](https://github.com/user-attachments/assets/0c4b26f2-b792-494b-9005-6047e972c14b)
我跑了很多轮的任务，日志的输出都大差不差是这样的，请问如何解决。

**Comment by ourines** [comment]
尝试解决方式：修改启动的 URL（site），根据日志信息来看是一个私有（需要登录的网站），且会重定向导致超时。

**Comment by ipv6ok** [comment]
主要原因还是大模型没有配置对。或大模型的API性能不足导致 的。 你试试换一家API。如deepseek之类的。
