### ISSUE TITLE
运行run.sh有[asyncio] ERROR Task exception was never retrieved报错

### ISSUE THREAD

**Issue by lp19910807** [TeamWiseFlow/wiseflow#164]
![image](https://github.com/user-attachments/assets/4703e68e-15c4-42e5-8355-4f563cafa8d4)
大神帮看下这个错误，系统centos7.9 使用本地glm-4-9b-chat    
![image](https://github.com/user-attachments/assets/f1f61277-9c9e-460d-8027-79a97c137310)

**Comment by bigbrother666sh** [comment]
看起来是你本地 playwright 的问题，crawlee 需要安装 crawlee['playwrigt']，另外需要执行 playwright install。
除此之外，你使用本地部署的 llm，需要把 primary_model 和 secondary_model 都设置为本地 engine支持的 mode 型号

**Comment by lp19910807** [comment]
已解决，升级GLIBC

**Comment by lp19910807** [comment]
> 看起来是你本地 playwright 的问题，crawlee 需要安装 crawlee['playwrigt']，另外需要执行 playwright install。 除此之外，你使用本地部署的 llm，需要把 primary_model 和 secondary_model 都设置为本地 engine支持的 mode 型号

ok 多谢
