### ISSUE TITLE
运行程序之后采集失败

### ISSUE THREAD

**Issue by hotjack55** [TeamWiseFlow/wiseflow#18]
core-1  | INFO:     Started server process [19]
core-1  | INFO:     Waiting for application startup.
core-1  | INFO:     Application startup complete.
core-1  | 2024-07-13 13:33:55.431 | INFO     | insights:pipeline:45 - publish date is 20240303, too old, skip
core-1  | 2024-07-13 13:33:55.632 | INFO     | insights:pipeline:45 - publish date is 20240303, too old, skip
core-1  | 2024-07-13 13:33:55.650 | INFO     | insights:pipeline:45 - publish date is 20240628, too old, skip
core-1  | 2024-07-13 13:33:55.878 | INFO     | insights:pipeline:45 - publish date is 20180409, too old, skip
core-1  | 2024-07-13 13:33:56.063 | INFO     | insights:pipeline:45 - publish date is 20180409, too old, skip

**Comment by hotjack55** [comment]
![Uploading 截屏2024-07-13 22.01.19.png…]()

**Comment by hotjack55** [comment]
<img width="1411" alt="截屏2024-07-13 22 01 19" src="https://github.com/user-attachments/assets/c3a136cf-1756-450d-845f-eb700b62f063">

**Comment by bigbrother666sh** [comment]
这不是运行失败，这已经运行成功了，只是抓取到的信源太旧，目前是设定只抓取前三天的信息

**Comment by jmanhype** [comment]
how to change this?

**Comment by bigbrother666sh** [comment]
core/insights/__init__.py  更改这里面的 expiration_date
