### ISSUE TITLE
建立了 admin 账号，但是重启程序后，仍然报错，同时 无法访问127.0.0.1:8090

### ISSUE THREAD

**Issue by CwjZzzy** [TeamWiseFlow/wiseflow#19]
![1](https://github.com/user-attachments/assets/e5724eea-b437-418c-b54e-d85fda099377)
![image](https://github.com/user-attachments/assets/7f1cc7e6-9340-4f28-94cd-dbaa00e08f0f)
![image](https://github.com/user-attachments/assets/137d17aa-3dbe-474e-a10a-24b21abb0b07)

报错日志为 ：core-1  | Process SpawnProcess-1:
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 21, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 81, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 125, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.utils.ClientResponseError: Response error. Status code:400
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
core-1  |     self.run()
core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
core-1  |     self._target(*self._args, **self._kwargs)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
core-1  |     target(sockets=sockets)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
core-1  |     return asyncio.run(self.serve(sockets=sockets))
core-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
core-1  |     return loop.run_until_complete(main)
core-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
core-1  |     await self._serve(sockets)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
core-1  |     config.load()
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
core-1  |     self.loaded_app = import_from_string(self.app)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
core-1  |     module = importlib.import_module(module_str)
core-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
core-1  |     return _bootstrap._gcd_import(name[level:], package, level)
core-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
core-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
core-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
core-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
core-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
core-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
core-1  |   File "/app/backend.py", line 5, in <module>
core-1  |     from insights import message_manager
core-1  |   File "/app/insights/__init__.py", line 5, in <module>
core-1  |     from .get_info import get_info, pb, project_dir, logger, info_rewrite
core-1  |   File "/app/insights/get_info.py", line 27, in <module>
core-1  |     pb = PbTalker(logger)
core-1  |   File "/app/utils/pb_api.py", line 25, in __init__
core-1  |     user_data = self.client.collection("users").auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 173, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 125, in send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.utils.ClientResponseError: Response error. Status code:400

env的配置为 ：
![image](https://github.com/user-attachments/assets/9baa9450-cbe9-4133-8c29-72e0ae3eb635)
来个大佬帮忙看下，

**Comment by stack3mpty** [comment]
我也遇到了这个问题

**Comment by CwjZzzy** [comment]
重新尝试了N次，已经解决了。 在.env 的配置文件中，export PB_API_AUTH="*|1234567890"， 使用这个替换原先的，*号替换为自己的邮箱即可，密码与这个一致，在初始的 env_sample 文件，定义的密码（123467890）错误， 不符合最少10位的要求。
