### ISSUE TITLE
请问微信公众号该如何填列表url?

### ISSUE THREAD

**Issue by swizardlv** [TeamWiseFlow/wiseflow#2]
如题

谢谢！

**Comment by bigbrother666sh** [comment]
公众号历史文章列表url已经被腾讯封禁，无法通过任何浏览器（包括模拟器）获取，
也许可以参考这个 https://blog.csdn.net/kuailebuzhidao/article/details/136490529
【另一个兄弟提供的方案】，
我们实践中是使用wxbot, 实时获得微信公众号publicmsg
