### ISSUE TITLE
容器跑起来了,但抓取不了数据

### ISSUE THREAD

**Issue by ranuyuy** [TeamWiseFlow/wiseflow#20]
日志打印api key的问题
![1](https://github.com/user-attachments/assets/f1eb75d5-c352-4776-a510-0e26071d0e6d)

**Comment by hwei-hw** [comment]
看起来是要设置OpenAI的api_key,里面调用了OpenAI的模型

**Comment by ranuyuy** [comment]
已搞定,谢谢指导

**Comment by ranuyuy** [comment]
> 看起来是要设置OpenAI的api_key，里面调用了OpenAI的模型
谢谢
