### ISSUE TITLE
全部配置好，但完全不知道数据怎么爬

### ISSUE THREAD

**Issue by hanlintao** [TeamWiseFlow/wiseflow#21]
已经配置好tag和site，然后两眼茫然，我现在应该干什么？

**Comment by JasonFangGOD** [comment]
我已经在自己电脑上部署好了项目，但是两眼黑，还在摸索中，如果有大佬搞好了可以踢我一下嘛，在线蹲

**Comment by moyuguy** [comment]
> 已经配置好tag和site，然后两眼茫然，我现在应该干什么？

我跟你一样，配置完之后它啥也不干。晚上回来启动了，就开始自己爬站点了，停都停不下来。。。。

**Comment by ChaHaiTang** [comment]
@moyuguy 我现在也是爬取到了数据，我跟开发者联系后询问到的结果是可以自己进行二开，也可以自行对接api进行新程序编写

**Comment by hotjack55** [comment]
> > 已经配置好tag和site，然后两眼茫然，我现在应该干什么？
> 
> 我跟你一样，配置完之后它啥也不干。晚上回来启动了，就开始自己爬站点了，停都停不下来。。。。

请教兄弟,你爬取的时候填了site吗,还是只需要填tag

**Comment by moyuguy** [comment]
> > > 已经配置好tag和site，然后两眼茫然，我现在应该干什么？
> > 
> > 
> > 我跟你一样，配置完之后它啥也不干。晚上回来启动了，就开始自己爬站点了，停都停不下来。。。。
> 
> 请教兄弟,你爬取的时候填了site吗,还是只需要填tag

需要填sites的url和per_hour，看了源码就是定时抓你填的url的内容。最快每小时抓一次，但是它建议频次不要太高一天一次

**Comment by bigbrother666sh** [comment]
http://127.0.0.1:8090/_/ 

浏览器打开这里看结果，本来wiseflow设计就是定时监控跟踪相关信源

**Comment by jmanhype** [comment]
insights dont work 

im in US so im using open ai base
