### ISSUE TITLE
设置的tag和抓取的内容不一致

### ISSUE THREAD

**Issue by hotjack55** [TeamWiseFlow/wiseflow#22]
<img width="634" alt="截屏2024-07-24 02 41 31" src="https://github.com/user-attachments/assets/46de7a28-852e-4843-bca5-c4ee5467e83f">
<img width="534" alt="截屏2024-07-24 02 41 22" src="https://github.com/user-attachments/assets/c81db0e2-668a-47f9-a061-73409374412a">
填了一个新闻网址,然后得到的抓取内容和tag完全不一致

**Comment by bigbrother666sh** [comment]
要看insight页面

**Comment by hotjack55** [comment]
> 要看insight页面

insight页面打开全部是空白呢
<img width="1013" alt="截屏2024-07-30 08 58 37" src="https://github.com/user-attachments/assets/ba24fe6a-be2b-4959-9ca8-c22eece00006">

**Comment by bigbrother666sh** [comment]
那就说明给定的信息源中还没有匹配兴趣点的内容

**Comment by jmanhype** [comment]
nah bro it just doenst work

**Comment by ccxxiicc** [comment]
@jmanhype 请问你能获取insight吗？我这块日志一直报错
