### ISSUE TITLE
 httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

### ISSUE THREAD

**Issue by rgzhang1231321** [TeamWiseFlow/wiseflow#3]
我在使用docker运行的时候，报错：Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
core-1  |     yield
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
core-1  |     resp = self._pool.handle_request(req)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 214, in handle_request
core-1  |     raise UnsupportedProtocol(
core-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | The above exception was the direct cause of the following exception:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 95, in _send
core-1  |     response = self.http_client.request(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
core-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
core-1  |     response = self._send_handling_auth(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
core-1  |     response = self._send_handling_redirects(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
core-1  |     response = self._send_single_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
core-1  |     response = transport.handle_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
core-1  |     with map_httpcore_exceptions():
core-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
core-1  |     self.gen.throw(typ, value, traceback)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
core-1  |     raise mapped_exc(message) from exc
core-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 20, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 81, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 119, in send
core-1  |     response = self._send(path, req_config)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 106, in _send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.utils.ClientResponseError: General request error. Original error: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
core-1  |     yield
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
core-1  |     resp = self._pool.handle_request(req)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 214, in handle_request
core-1  |     raise UnsupportedProtocol(
core-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | The above exception was the direct cause of the following exception:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 95, in _send
core-1  |     response = self.http_client.request(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
core-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
core-1  |     response = self._send_handling_auth(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
core-1  |     response = self._send_handling_redirects(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
core-1  |     response = self._send_single_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
core-1  |     response = transport.handle_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
core-1  |     with map_httpcore_exceptions():
core-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
core-1  |     self.gen.throw(typ, value, traceback)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
core-1  |     raise mapped_exc(message) from exc
core-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/app/tasks.py", line 2, in <module>
core-1  |     from insights import pipeline, pb, logger
core-1  |   File "/app/insights/__init__.py", line 5, in <module>
core-1  |     from .get_info import get_info, pb, project_dir, logger, info_rewrite
core-1  |   File "/app/insights/get_info.py", line 27, in <module>
core-1  |     pb = PbTalker(logger)
core-1  |   File "/app/utils/pb_api.py", line 24, in __init__
core-1  |     user_data = self.client.collection("users").auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 173, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 119, in send
core-1  |     response = self._send(path, req_config)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 106, in _send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.utils.ClientResponseError: General request error. Original error: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 2024-06-26 07:45:30.439 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: 127.0.0.1:8091
core-1  | Process SpawnProcess-1:
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
core-1  |     yield
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
core-1  |     resp = self._pool.handle_request(req)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 214, in handle_request
core-1  |     raise UnsupportedProtocol(
core-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | The above exception was the direct cause of the following exception:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 95, in _send
core-1  |     response = self.http_client.request(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
core-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
core-1  |     response = self._send_handling_auth(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
core-1  |     response = self._send_handling_redirects(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
core-1  |     response = self._send_single_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
core-1  |     response = transport.handle_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
core-1  |     with map_httpcore_exceptions():
core-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
core-1  |     self.gen.throw(typ, value, traceback)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
core-1  |     raise mapped_exc(message) from exc
core-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/app/utils/pb_api.py", line 20, in __init__
core-1  |     admin_data = self.client.admins.auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/admin_service.py", line 81, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 119, in send
core-1  |     response = self._send(path, req_config)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 106, in _send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.utils.ClientResponseError: General request error. Original error: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
core-1  |     yield
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
core-1  |     resp = self._pool.handle_request(req)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 214, in handle_request
core-1  |     raise UnsupportedProtocol(
core-1  | httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | The above exception was the direct cause of the following exception:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 95, in _send
core-1  |     response = self.http_client.request(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
core-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
core-1  |     response = self._send_handling_auth(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
core-1  |     response = self._send_handling_redirects(
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
core-1  |     response = self._send_single_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
core-1  |     response = transport.handle_request(request)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
core-1  |     with map_httpcore_exceptions():
core-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
core-1  |     self.gen.throw(typ, value, traceback)
core-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
core-1  |     raise mapped_exc(message) from exc
core-1  | httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
core-1  | 
core-1  | During handling of the above exception, another exception occurred:
core-1  | 
core-1  | Traceback (most recent call last):
core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
core-1  |     self.run()
core-1  |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
core-1  |     self._target(*self._args, **self._kwargs)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
core-1  |     target(sockets=sockets)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
core-1  |     return asyncio.run(self.serve(sockets=sockets))
core-1  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
core-1  |     return loop.run_until_complete(main)
core-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
core-1  |     await self._serve(sockets)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
core-1  |     config.load()
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
core-1  |     self.loaded_app = import_from_string(self.app)
core-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
core-1  |     module = importlib.import_module(module_str)
core-1  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
core-1  |     return _bootstrap._gcd_import(name[level:], package, level)
core-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
core-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
core-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
core-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
core-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
core-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
core-1  |   File "/app/backend.py", line 5, in <module>
core-1  |     from insights import message_manager
core-1  |   File "/app/insights/__init__.py", line 5, in <module>
core-1  |     from .get_info import get_info, pb, project_dir, logger, info_rewrite
core-1  |   File "/app/insights/get_info.py", line 27, in <module>
core-1  |     pb = PbTalker(logger)
core-1  |   File "/app/utils/pb_api.py", line 24, in __init__
core-1  |     user_data = self.client.collection("users").auth_with_password(email, password)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/services/record_service.py", line 173, in auth_with_password
core-1  |     response_data = self.client.send(
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 119, in send
core-1  |     response = self._send(path, req_config)
core-1  |   File "/usr/local/lib/python3.10/site-packages/pocketbase/client.py", line 106, in _send
core-1  |     raise ClientResponseError(
core-1  | pocketbase.utils.ClientResponseError: General request error. Original error: Request URL is missing an 'http://' or 'https://' protocol.

这是我的.env文件内容：
export LLM_API_KEY="sk-xxxxxxxxxxx"
export LLM_API_BASE="https://api.siliconflow.cn/v1" ##for local model services or calling non-OpenAI services with openai_wrapper
##strongly recommended to use the following model provided by siliconflow (consider both effect and price)
export GET_INFO_MODEL="zhipuai/glm4-9B-chat"
export REWRITE_MODEL="alibaba/Qwen2-7B-Instruct"
export HTML_PARSE_MODEL="alibaba/Qwen2-7B-Instruct" ##or"01-ai/Yi-1.5-9B-Chat"
export PROJECT_DIR="work_dir"
export PB_API_AUTH="1135909556@qq.com|15619520551zrg"
export PB_API_BASE="127.0.0.1:8091" ##only use if your pb not run on 127.0.0.1:8090
export WS_LOG="verbose" ##for detail log info. If not need, just delete this item.

请问这是什么原因，非常感谢

**Comment by rgzhang1231321** [comment]
已解决，PB_API_BASE参数的问题

**Comment by Fredwu925** [comment]
@rgzhang1231321 请问PB_API_BASE 具体设置成什么？
