### ISSUE TITLE
https://127.0.0.1:8090/api提示{"code":404,"message":"Not Found.","data":{}}

### ISSUE THREAD

**Issue by wood1ng** [TeamWiseFlow/wiseflow#32]
我查看了文档并且api配置为https://docs.siliconflow.cn/docs/4-api%E8%B0%83%E7%94%A8
![image](https://github.com/user-attachments/assets/857491cd-4e95-46d4-9890-fd39f4d303e8)

已经配置好了sites和tags 并且配置之后尝试重启了docker 如何让他运行起来爬取数据呢
![image](https://github.com/user-attachments/assets/e5378921-5e91-4ee7-bd45-9bf03c4ec20d)
![image](https://github.com/user-attachments/assets/b6b5b6a9-d85d-4180-a943-a5a60bd45bf5)

**Comment by ZGY-110** [comment]
同问，希望可以出一个详细的实例教程！

**Comment by bigbrother666sh** [comment]
http://127.0.0.1:8090/_/
