### ISSUE TITLE
docker hub里面找不到wiseflow image

### ISSUE THREAD

**Issue by yuphone** [TeamWiseFlow/wiseflow#33]

**Comment by ninematrix** [comment]
传了一个ninematrix/wiseflow

**Comment by yuphone** [comment]
> 传了一个ninematrix/wiseflow

` ! core The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s `

不支持mac M系列处理器呀。

**Comment by QYG2297248353** [comment]
> 不支持mac M系列处理器呀。

您可以尝试使用 1Panel 应用商店的配置
https://github.com/QYG2297248353/appstore-1panel

![image](https://github.com/user-attachments/assets/b60655ed-ca09-42c0-9e2c-74bf8389b8e2)
