### ISSUE TITLE
部署好了，怎么用？

### ISSUE THREAD

**Issue by flyingpig-7** [TeamWiseFlow/wiseflow#34]
缺少一个具体的案例？
因为爬取公众号文章进来的，部署好了还是没法用。

**Comment by wwz223** [comment]
wiseflow是底层支持，完整的业务场景设计可以参考 TeamWiseFlow/awada 项目

**Comment by bigbrother666sh** [comment]
> 缺少一个具体的案例？ 因为爬取公众号文章进来的，部署好了还是没法用。

参考 https://github.com/TeamWiseFlow/awada 这个吧
