### ISSUE TITLE
没有爬取到数据

### ISSUE THREAD

**Issue by wood1ng** [TeamWiseFlow/wiseflow#36]
![image](https://github.com/user-attachments/assets/3b8b47fe-f06e-42e1-8eed-fa7900a58121)
![image](https://github.com/user-attachments/assets/621f208c-5501-43cb-9ae2-6cbfd7e88012)
填写好之后users article_translation页面  articles insights页面都没有数据
打开http://127.0.0.1:8090/_/自动跳转到uesr界面

**Comment by bigbrother666sh** [comment]
看看 docker container里面的日志？

**Comment by ShawshankLin** [comment]
@bigbrother666sh 这个只能一小时跑一次吗，可以手动触发跑吗？

**Comment by wood1ng** [comment]
![1723186188779](https://github.com/user-attachments/assets/d0ef6340-11ed-4236-a247-c246e14d8787)
![image](https://github.com/user-attachments/assets/df2ca61d-a170-42f3-99ec-56b25ad27cea)
![image](https://github.com/user-attachments/assets/47f0fd27-6099-411c-9124-12dd548cdbde)

![image](https://github.com/user-attachments/assets/fd7dc108-892f-43f2-b589-5bb6a2d1dd0b)

**Comment by bigbrother666sh** [comment]
> @bigbrother666sh 这个只能一小时跑一次吗，可以手动触发跑吗？

若要立刻执行，可以设定site的hour为1，然后重启。
