### ISSUE TITLE
请问下，对于一些有反扒措施的网站可以爬下来数据吗？比如小红书

### ISSUE THREAD

**Issue by rgzhang1231321** [TeamWiseFlow/wiseflow#4]
请问下，对于一些有反扒措施的网站可以爬下来数据吗？比如小红书

**Comment by bigbrother666sh** [comment]
需要定制专属爬虫，商用客户可邮件联系

**Comment by wwz223** [comment]
> 比如小红书

该项目核心功能是数据提取整理，自带一个通用爬虫工具，对于一些有反扒措施的网站，需要提供特定的爬虫程序进行对接；
像小红书爬虫目前github是有开源方案的
