### ISSUE TITLE
第一次使用Docker，不是很熟悉，求指点

### ISSUE THREAD

**Issue by YanzhenHuang** [TeamWiseFlow/wiseflow#46]
![image](https://github.com/user-attachments/assets/9ac02000-40fd-4806-8f39-785e5d63d855)
![image](https://github.com/user-attachments/assets/a5686ffd-ed8f-449e-826d-9825e1700890)

这是我的运行log和Docker Desktop界面。似乎有一个服务没有开起来，卡住了。没有命令行或GUI界面，但是pocketbase可以打开。

**Comment by QYG2297248353** [comment]
您可以尝试通过 1Panel 应用商店直接安装使用

https://github.com/QYG2297248353/appstore-1panel

![image](https://github.com/user-attachments/assets/6637133f-1327-4634-a6fa-e4bdf0e7e759)

**Comment by verigle** [comment]
docker compose -f compose.yml up -d --build
