### ISSUE TITLE
400错误和404错误 各种错误解决办法

### ISSUE THREAD

**Issue by x7780** [TeamWiseFlow/wiseflow#47]
各种错误都出现在连接Collections
就运行在docker能成功，安装在python自己的环境就不行
解决办法：
安装22.13版本
https://github.com/pocketbase/pocketbase/releases/tag/v0.22.13    #放在pb目录，注意一定要和自己系统对上，要不报错
pip安装 PocketBase Python SDK 要安装0.12.1 版本。
pip install pocketbase
数据库迁移
cd pb
./pocketbase migrate up
代码修改部分
utils里面的pb_api.py
admin_data = self.client.admins.auth_with_password(email, password)
改成
admin_data = self.client.admins.auth_with_password("test@example.com", "1234567890")
其他问题没发现，真坑安装了好几小时，就不想用docke

**Comment by AlLenNotFound** [comment]
遇到了一样的问题，但是还是没有解决

**Comment by cgrain1998** [comment]
我靠，真的谢谢你，task.py 死活进不去，搞了很久  ，看到你这个`` admin_data = self.client.admins.auth_with_password("[test@example.com](mailto:test@example.com)", "1234567890") `` 终于成功了

![image](https://github.com/user-attachments/assets/7683d5c0-c3d0-425a-ae44-7c5d4dd3d658)

![image](https://github.com/user-attachments/assets/33e9d5aa-07d5-48a2-aa3b-a39267298873)

页面上也一直错误
![image](https://github.com/user-attachments/assets/3a693df1-634a-4848-a448-bbe0b6953012)
现在成功了
