### ISSUE TITLE
跑起来，然后呢？

### ISSUE THREAD

**Issue by xinzhics** [TeamWiseFlow/wiseflow#5]
可以给下使用说明不，跑起来不知道怎么用。还有使用本地的大模型会报错
![Uploading image.png…]()

**Comment by xinzhics** [comment]
| openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by bigbrother666sh** [comment]
打开 127.0.0.1：8090/_/ 在sites表单中设置要监控的信源网站
本地大模型也需要设定key（随便写）和 base_url 
建议仔细阅读Readme，有中文版本
