### ISSUE TITLE
pocketbase.utils.ClientResponseError: Response error. Status code:400 是怎么回事?已经启动起来了,然后启动报错,后边所有的请求都是404

### ISSUE THREAD

**Issue by kevinfuture** [TeamWiseFlow/wiseflow#51]
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/27d13895-6abf-46db-9a1a-d821187b2a2f">

pocketbase请求404
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/4866caa3-d438-4773-b243-4eda739d214b">

**Comment by 34892002** [comment]
环境变量PB_API_AUTH里面配置的账号密码，添加到admin里面去

**Comment by kevinfuture** [comment]
> 环境变量PB_API_AUTH里面配置的账号密码，添加到admin里面去

可以了,感谢解答
