### ISSUE TITLE
请教,我安装成功后,配置了url,但是localhost:8090的页面打开时404的json字符串,并没有显示爬取什么的?更没有生成报告,怎么回事?

### ISSUE THREAD

**Issue by kevinfuture** [TeamWiseFlow/wiseflow#54]
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/6da5f01b-21bd-4f69-92f5-7dabff283480">

<img width="997" alt="image" src="https://github.com/user-attachments/assets/508c9b80-8b8b-445f-8de1-439317611d0b">

是否可以出一个详细的使用教程?或者视频

**Comment by bigbrother666sh** [comment]
http://localhost:8090/_/

**Comment by kevinfuture** [comment]
> http://localhost:8090/_/

第一个图就是http://localhost:8090/_/
但是我想看怎么做的情报的这个在哪里看?

**Comment by bigbrother666sh** [comment]
那需要打通Dashboard这块 ，可以见 #52
