### ISSUE TITLE
PB后台报错,数据也抓不到,求解

### ISSUE THREAD

**Issue by xiaoaqiu2023** [TeamWiseFlow/wiseflow#56]
pb也启动起来了,docker启动就报错,已按照要求添加了tags和sites,并检查了.evn确定未填写错误,请问这个报错有影响吗?我该如何处理.
![23](https://github.com/user-attachments/assets/34f1886a-9031-421f-b9f0-7fd4209db45a)

**Comment by bigbrother666sh** [comment]
这提示不是很明显吗，你数据库设定的账密跟env里面是不是一样？

**Comment by xiaoaqiu2023** [comment]
> 这提示不是很明显吗，你数据库设定的账密跟env里面是不是一样？

我确定是100%一样的，改了多次，对了多次

**Comment by bigbrother666sh** [comment]
要在 .env 的PB_API_AUTH 配置，username|password 格式。另外你截图中docker_entrypoint.sh报错是怎么回事？改动过这个文件，可以一并排查下
