### ISSUE TITLE
CondaError: Run 'conda init' before 'conda activate'

### ISSUE THREAD

**Issue by lihuadong** [TeamWiseFlow/wiseflow#57]
conda create -n wiseflow python=3.10
conda activate wiseflow
cd core
pip install -r requirements.txt

在执行第二行时，提示如标题内容“CondaError: Run 'conda init' before 'conda activate'”，但是执行 conda  init 之后，依然无效。

谢谢

**Comment by bigbrother666sh** [comment]
那是你conda安装有问题了，可以看下是否添加了路径
