### ISSUE TITLE
怎样配置远程访问

### ISSUE THREAD

**Issue by hy-yq** [TeamWiseFlow/wiseflow#58]
本地可以运行，但是远程无法访问，应该怎样修改配置为监听所有可用的网络接口，而不仅仅是本地回环地址（127.0.0.1），没有找到相关的pocketbase配置文件 和修改 Uvicorn 的监听地址的地方

**Comment by bigbrother666sh** [comment]
可以看看这里 core/docker_entrypoint.sh

理论上默认就是 监听 0.0.0.0 , 但如果你用的是docker，还需要配置下docker的暴露地址。另外跟你的网络和操作系统也有关系（比如windows的网络就比较麻烦）

**Comment by dengdylan8** [comment]
镜像下载到本地，再打包到服务器上运行，本地可以运行，服务器启动服务，web页面无法访问，服务器运行命令：docker run -d --name wiseflow -p 8090:8090 -p 8077:8077 wiseflow:latest
还需要做其他设置吗？
