### ISSUE TITLE
404,Detail not found

### ISSUE THREAD

**Issue by Maple-smx** [TeamWiseFlow/wiseflow#59]
![image](https://github.com/user-attachments/assets/55450f91-65a6-4c28-8fd5-ae15c52c6f08)

**Comment by Maple-smx** [comment]
![image](https://github.com/user-attachments/assets/4a2e66d5-2a10-4fc6-8871-c68a429c7b84)

**Comment by bigbrother666sh** [comment]
没有配置 LLM_API_BASE
和 LLM_API_KEY？

**Comment by Maple-smx** [comment]
配置了的,所以才不明白这个保存是啥原因
