### ISSUE TITLE
访问http://localhost:8090/报错404

### ISSUE THREAD

**Issue by lutixiaya** [TeamWiseFlow/wiseflow#6]
项目通过docker部署，看日志像是正常启动了。
<img width="972" alt="image" src="https://github.com/TeamWiseFlow/wiseflow/assets/48750425/abf94cb9-6cde-45a2-9530-ec79b3d3d94e">
也可以访问Admin UI，并且配置tags等。
<img width="1067" alt="image" src="https://github.com/TeamWiseFlow/wiseflow/assets/48750425/049fc090-bdba-45d6-895f-1b11e9ff9a00">

但是访问8090端口报404：
<img width="625" alt="image" src="https://github.com/TeamWiseFlow/wiseflow/assets/48750425/83906e8f-0485-47b0-87f0-441f1288702f">

目录权限是没有问题的，不知道还是哪里的问题？

**Comment by lutixiaya** [comment]
自查出了一个问题，我是M系列的mac系统，需要修改Dockerfile文件，拉取arm架构的pocketbase包，但没有解决上面的问题。
<img width="965" alt="image" src="https://github.com/TeamWiseFlow/wiseflow/assets/48750425/5368fcc4-e8d0-4f2e-9326-83045d42bc59">

**Comment by wwz223** [comment]
> 项目通过docker部署，看日志像是正常启动了。 <img alt="image" width="972" src="https://private-user-images.githubusercontent.com/48750425/344885509-abf94cb9-6cde-45a2-9530-ec79b3d3d94e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjE1OTIsIm5iZiI6MTcyMDA2MTI5MiwicGF0aCI6Ii80ODc1MDQyNS8zNDQ4ODU1MDktYWJmOTRjYjktNmNkZS00NWEyLTk1MzAtZWM3OWIzZDNkOTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNjJlNTI1ZjZlOTAxMzJhMGIwNTVmODY0N2U0OTE3ZDNkZmRiYTk5MTkyNDJjYTc1ZTc0ZWIzMWU1MjgxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVqjf8y9Eb_CNgD6IIuPljV8-hWM2v-3Hg2gY9ji__4"> 也可以访问Admin UI，并且配置tags等。 <img alt="image" width="1067" src="https://private-user-images.githubusercontent.com/48750425/344885637-049fc090-bdba-45d6-895f-1b11e9ff9a00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjE1OTIsIm5iZiI6MTcyMDA2MTI5MiwicGF0aCI6Ii80ODc1MDQyNS8zNDQ4ODU2MzctMDQ5ZmMwOTAtYmRiYS00NWQ2LTg5NWYtMWIxMWU5ZmY5YTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZmRmNTg3NWU1OTFiMDgyMWI4M2E0NGM3MGIyOTNkNzlmYTYyMWEyMmQ4ZTljOTYyOWQ0MmE5MDMwYWNmOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vWRxLIpvSjkxVucsvpmRutBg2omF9-dzogn-SwojYn8">
> 
> 但是访问8090端口报404： <img alt="image" width="625" src="https://private-user-images.githubusercontent.com/48750425/344885713-83906e8f-0485-47b0-87f0-441f1288702f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjE1OTIsIm5iZiI6MTcyMDA2MTI5MiwicGF0aCI6Ii80ODc1MDQyNS8zNDQ4ODU3MTMtODM5MDZlOGYtMDQ4NS00N2IwLTg3ZjAtNDQxZjEyODg3MDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyNDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMGIyMDY0ZDhlMDFhODlmYjFiY2ZjYjAwNjdiMWM2MzM2MjA1ZTJlYWZiYjQ1ZWIwZTM4YzZmZjJjOTVjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.643J5Vb0wzJHHIQhPK4kVXshln44LHJs2N1gM0LxbgQ">
> 
> 目录权限是没有问题的，不知道还是哪里的问题？

<img width="957" alt="image" src="https://github.com/TeamWiseFlow/wiseflow/assets/36815297/801b011c-e605-4da1-bca1-6ad32f8fdc40">
这个错误应该没什么影响吧

**Comment by rans0mban** [comment]
同样的问题，没有信息能获取到。。
有人部署成功吗？

**Comment by cced3000** [comment]
同样问题，部署没成功。等解决方法

**Comment by wwz223** [comment]
> 同样的问题，没有信息能获取到。。 有人部署成功吗？

我这边部署成功了，没有信息能获取到是什么意思？需要先在pocketbase 站点的sites菜单栏下面添加需要爬取的网页链接

**Comment by jacktang365** [comment]
同样的问题，没有信息能获取到。。

**Comment by niccolashank** [comment]
> > 同样的问题，没有信息能获取到。。 有人部署成功吗？
> 
> 我这边部署成功了，没有信息能获取到是什么意思？需要先在pocketbase 站点的sites菜单栏下面添加需要爬取的网页链接

我也和楼主一样的问题，访问localhost:8090，报错404
`{
    "code": 404,
    "message": "Not Found.",
    "data": {}
}`

但是部署是正常的，也能够正常启动，且配置了sites目标网页和tags逻辑词条。
`root@OpenWrt:/mnt/sda3/docker/docker_hub/Wiseflow# docker compose up
[+] Running 2/2
 ✔ Network wiseflow_default   Created                                                                                                0.1s
 ✔ Container wiseflow-core-1  Created                                                                                                0.1s
Attaching to core-1
core-1  | bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
core-1  | 2024/07/13 12:17:16 Server started at http://0.0.0.0:8090
core-1  | ├─ REST API: http://0.0.0.0:8090/api/
core-1  | └─ Admin UI: http://0.0.0.0:8090/_/
core-1  | INFO:     Will watch for changes in these directories: ['/app']
core-1  | INFO:     Uvicorn running on http://0.0.0.0:8077 (Press CTRL+C to quit)
core-1  | INFO:     Started reloader process [1] using WatchFiles
core-1  | 2024-07-13 12:17:18.288 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://xianzhou.xyz:8090
core-1  | 2024-07-13 12:17:18.701 | INFO     | utils.pb_api:__init__:22 - pocketbase ready authenticated as admin - ychukunrt@qq.com
core-1  | 2024-07-13 12:17:18.736 | INFO     | __main__:schedule_pipeline:19 - task execute loop 1
core-1  | 2024-07-13 12:17:18.737 | INFO     | __main__:schedule_pipeline:23 - task execute loop finished, work after 3600 seconds
core-1  | 2024-07-13 12:17:19.489 | DEBUG    | utils.pb_api:__init__:12 - initializing pocketbase client: http://xianzhou.xyz:8090
core-1  | 2024-07-13 12:17:19.905 | INFO     | utils.pb_api:__init__:22 - pocketbase ready authenticated as admin - ychukunrt@qq.com
core-1  | INFO:     Started server process [19]
core-1  | INFO:     Waiting for application startup.
core-1  | INFO:     Application startup complete.`

引申出来还有两个问题：
1、容器部署成功后，写入tags和sites规则后，系统是否会自动爬一遍这些网页？或者是需要重新再启动一下容器？
2、目前提示的404错误，写的是Not Found，是不是还没有爬到对应信息的意思？

**Comment by scufox** [comment]
一脸懵也是，等一个小时他会自动爬取么还是

**Comment by bigbrother666sh** [comment]
http://127.0.0.1:8090/_/

**Comment by thinkvisionjin** [comment]
> 一脸懵也是，等一个小时他会自动爬取么还是

我等了一个小时，自动爬了，但是爬的内容很少，另外[http://127.0.0.1:8090/](http://127.0.0.1:8090/）这个链接还是
{
    "code": 404,
    "message": "Not Found.",
    "data": {}
}
有哪位大佬知道怎么进行搜索？

**Comment by wisepmlin** [comment]
{"code":404,"message":"Not Found.","data":{}}也是这个问题，希望快点修复

**Comment by Wang-Mer** [comment]
> http://127.0.0.1:8090/_/

这个是可以访问的，说明文档不会看吗？英文看不懂 翻译啊
