### ISSUE TITLE
配置好了不知道怎么用

### ISSUE THREAD

**Issue by zsw12abc** [TeamWiseFlow/wiseflow#60]
我按照env_sample创建了.env文件
用了免费的LLM_API_KEY, 更新了PB_API_AUTH (第一次登录dashboard创建的)
登录了dashboard
加入了tags
但是不知道怎么抓取信息
求教~

**Comment by zsw12abc** [comment]
![image](https://github.com/user-attachments/assets/544a6ef5-53ee-4e30-87c1-e6da4e867589)
我明明更新了语言和时区
为啥重新运行后还是UTC时间?

**Comment by bigbrother666sh** [comment]
尝试这样启动 docker run -e LANG=zh_CN.UTF-8 -e LC_CTYPE=zh_CN.UTF-8 your_image
配置好了，它后台会自己运行，你按设定的时间去看 http://127.0.0.1:8090/_/ 看就行了啊

**Comment by zsw12abc** [comment]
所以是这样么?
![image](https://github.com/user-attachments/assets/f750cb5c-1239-41c0-943b-44f272a7fa48)
![image](https://github.com/user-attachments/assets/2b2cf543-73ab-4788-94e3-053691459d66)
这些是不是意味着后台已经自己在抓取信息了?
但是我tags或者网站没设置对 所以什么都没有?

**Comment by bigbrother666sh** [comment]
你 sites 和 tags设定为 activate了么？sites和tags更新需要重启container

**Comment by zsw12abc** [comment]
![image](https://github.com/user-attachments/assets/1bedaaf2-3d1a-47f4-bb42-6899be219c6b)
![image](https://github.com/user-attachments/assets/7067bd07-b945-473b-b644-961b927c94a1)
![image](https://github.com/user-attachments/assets/ce830809-f3b2-4343-a2b7-27023a10ec69)
我都打开了
而且已经重启过了
还是啥都没有
是不是我关键字tags有啥问题?

**Comment by bigbrother666sh** [comment]
你设定的是10个小时扫一次，所以你应该保持程序连续运行至少10小时及以上才能看到结果

**Comment by zsw12abc** [comment]
原来如此... 
谢谢~~
