### ISSUE TITLE
已经部署了awada，该如何操作获取微信公众号信息

### ISSUE THREAD

**Issue by airyyan** [TeamWiseFlow/wiseflow#61]
启动了wiseflow和wxbot，运行awada程序后，不知道要怎么去获取公众号的信息
![image](https://github.com/user-attachments/assets/c7af914b-5747-4be2-8b35-702b3847459d)
![image](https://github.com/user-attachments/assets/5682b16d-98d7-4e3b-9e78-0bcba9969272)
![image](https://github.com/user-attachments/assets/467a3018-3a53-41d4-944d-b57064aa2efa)
运行到python dm.py 就没有任何动静了。
也不知道在wiseflow中需要做些什么
![image](https://github.com/user-attachments/assets/2ae0a939-6dc8-4493-a01a-c438a9997592)
监控的信息源中是不是要添加需要监视的公众号id？但是别人的公众号id也不知道怎么能获取到。

**Comment by bigbrother666sh** [comment]
wiseflow是不需要额外配置什么的，公众号id无需添加，现在是默认监控所有已关注的公众号发来的信息。

你这个问题看起来还是wxbot不通啊，你查查看防火墙

**Comment by airyyan** [comment]
请问awada代码中的watching_list需要修改吗？抓取已关注的公众号的消息是只能抓发来的信息还是历史的信息也能抓取？抓取到的信息可以根据关键词提炼吗？最后抓取到的数据是都汇总到wiseflow中吗？

**Comment by airyyan** [comment]
![image](https://github.com/user-attachments/assets/f8c4b499-ab80-47c5-a3b8-e32d6d81c821)
wxbot这样不算启动吗？
当微信收到公众号消息时，awada就会报错：
![image](https://github.com/user-attachments/assets/925e1ff0-2a5d-4f17-a612-d9d924998ab6)

**Comment by airyyan** [comment]
直接部署到Linux服务器上：
wxbot启动正常：
![image](https://github.com/user-attachments/assets/25e8aa70-4de4-4f32-bc29-eb2d8e61e104)
但是awada还是启动后没有任何变化：
![image](https://github.com/user-attachments/assets/df636705-2569-4bb5-90d5-f3803b8a88b9)
wiseflow也是启动正常的。这要如何处理？

**Comment by bigbrother666sh** [comment]
需要把wxbot的端口改为8066，或者改awada的dm.py中ws的监听地址

是的，最后的信息都是汇总到wiseflow

**Comment by airyyan** [comment]
我是在docker中映射了wxbot的端口为8066
![image](https://github.com/user-attachments/assets/c226ed36-9355-4569-900b-5a04f65f60dc)
awada的dm.py中也改了ip地址，但是awada启动后没有任何输出。
今天看到awada日志里有如下报错：
![image](https://github.com/user-attachments/assets/75a38be7-a90d-4327-aca6-e198ee2348bc)

**Comment by airyyan** [comment]
我发现这个微信号好像从手机上登出之后，wxbot的微信也会被登出，然后就监控不到公众号信息了？
