### ISSUE TITLE
openai_llm error: Connection error.

### ISSUE THREAD

**Issue by zy1257** [TeamWiseFlow/wiseflow#62]
2024-08-16 14:57:15.356 | DEBUG    | llms.openai_wrapper:openai_llm:17 - messages:
 [{'role': 'system', 'content': "Please carefully read the user-inputted news content and analyze it based on the provided list of categories:\n['中秋节']\n\nIf the news contains any information related to the above categories, mark the type of information using the following format and provide a one-sentence summary containing only the time, location, who involved, and the event:\n<tag>Category Name</tag> One-sentence summary including only time, location, who, and event.\n\nIf the news includes multiple pieces of information, analyze each one separately and output them in a line-by-line format. If the news does not involve any of the listed categories, simply output: N/A.\nImportant guidelines to follow: 1) Adhere strictly to the original news content, do not provide information not contained in the original text; 2) For the same event, select only the most fitting tag, avoiding duplicate outputs; 3) Summarize using just one sentence, and limit it to time, location, who, and event only; 4) Strictly comply with the given output format."}, {'role': 'user', 'content': 'title: 2024年中秋、国庆假期安排，请查收！\n\ncontent: [from news] 新闻频道\n>\n中国新闻\n2024年中秋、国庆假期安排，请查收！\n来源：\n央视新闻\n| 2024年08月14日 18:00:09\n央视新闻 | 2024年08月14日 18:00:09\n原标题：\n正在加载\n中秋节、国庆节\n假期就要到了\n放假安排请查收\n↓\n↓\n中秋节\n9月15日至17日放假调休\n共3天\n9月14日（星期六）上班\n国庆节\n10月1日至7日放假调休\n共7天\n9月29日（星期日）\n10月12日（星期六）\n上班\n想要出游的小伙伴\n赶紧计划起来吧'}]
2024-08-16 14:57:15.356 | DEBUG    | llms.openai_wrapper:openai_llm:18 - model: alibaba/Qwen2-7B-Instruct
2024-08-16 14:57:15.356 | DEBUG    | llms.openai_wrapper:openai_llm:19 - kwargs:
 {'temperature': 0.1}
2024-08-16 14:57:18.872 | ERROR    | llms.openai_wrapper:openai_llm:26 - **_openai_llm error: Connection error._**
2024-08-16 14:57:18.872 | INFO     | insights.get_info:get_info:71 - can not find info, llm result:

2024-08-16 14:57:18.873 | INFO     | __main__:schedule_pipeline:23 - task execute loop finished, work after 3600 seconds

已经在siliconflow 里面生成了密钥

**Comment by bigbrother666sh** [comment]
LLM_API_BASE
设了么么

**Comment by zy1257** [comment]
![image](https://github.com/user-attachments/assets/e91a2e9c-39d0-4ebf-8826-03734beadad1)
设置了的

**Comment by bigbrother666sh** [comment]
重新生成docker image再试试看。

**Comment by zy1257** [comment]
改用 sfa_llm 可以跑通

**Comment by bigbrother666sh** [comment]
sillionflow 的sddk 包装器……实际用不上，因为 sillionflow 也支持 openai sdk
