### ISSUE TITLE
项目已经部署，请问怎么启动收集信息？

### ISSUE THREAD

**Issue by MTD-xiaoma** [TeamWiseFlow/wiseflow#63]
项目已经docker部署起来了。请问怎么收集信息？收集信息的入口在哪里？

docker部署起来log
![Snipaste_2024-08-16_14-43-10](https://github.com/user-attachments/assets/2a2f6bfa-cc74-4dc5-8621-9234b851f372)

启动了dashboard/web下面的前端。
![Snipaste_2024-08-16_14-46-49](https://github.com/user-attachments/assets/0485e267-7f42-467b-9039-52273f91c6f8)

进入上一步启动的前端页面
![image](https://github.com/user-attachments/assets/1351433c-c770-4aa9-8815-6f50a63dd5d7)

进入数据库管理，也没有任何数据
![image](https://github.com/user-attachments/assets/a3b70dd8-a27c-41ec-9f1b-aba010e2d4d5)

**Comment by airyyan** [comment]
6.1 打开 **tags表单**

 通过这个表单可以指定你的关注点，LLM会按此提炼、过滤并分类信息。

 tags 字段说明：

 - name, 关注点描述，**注意：要具体一些**，好的例子是：`中美竞争动向`，不好的例子是：`国际局势`。
 - activated, 是否激活。如果关闭则会忽略该关注点，关闭后可再次开启。开启和关闭无需重启docker容器，会在下一次定时任务时更新。


 6.2 打开 **sites表单**

 通过这个表单可以指定自定义信源，系统会启动后台定时任务，在本地执行信源扫描、解析和分析。

 sites 字段说明：

 - url, 信源的url，信源无需给定具体文章页面，给文章列表页面即可。
 - per_hours, 扫描频率，单位为小时，类型为整数（1~24范围，我们建议扫描频次不要超过一天一次，即设定为24）
 - activated, 是否激活。如果关闭则会忽略该信源，关闭后可再次开启。开启和关闭无需重启docker容器，会在下一次定时任务时更新。

然后重启container

**Comment by fangyu6** [comment]
@bigbrother666sh  您好，请问一下，在sites中添加URL，tags中添加name后，该如何查看抓取的信息呀

**Comment by bigbrother666sh** [comment]
http://127.0.0.1:8090/_/ 
点 insgiht

**Comment by fangyu6** [comment]
@bigbrother666sh 点击 insgiht后没有内容，请问下您知道http://localhost:5173/情报分析的网站该怎么登录嘛，和PocketBase网页同一个用户名和密码吗，没看到注册的地方，访问5173的网址直接就是登录页面

**Comment by bigbrother666sh** [comment]
> @bigbrother666sh 点击 insgiht后没有内容，请问下您知道[http://localhost:5173/情报分析的网站该怎么登录嘛，和PocketBase网页同一个用户名和密码吗，没看到注册的地方，访问5173的网址直接就是登录页面](http://localhost:5173/%E6%83%85%E6%8A%A5%E5%88%86%E6%9E%90%E7%9A%84%E7%BD%91%E7%AB%99%E8%AF%A5%E6%80%8E%E4%B9%88%E7%99%BB%E5%BD%95%E5%98%9B%EF%BC%8C%E5%92%8CPocketBase%E7%BD%91%E9%A1%B5%E5%90%8C%E4%B8%80%E4%B8%AA%E7%94%A8%E6%88%B7%E5%90%8D%E5%92%8C%E5%AF%86%E7%A0%81%E5%90%97%EF%BC%8C%E6%B2%A1%E7%9C%8B%E5%88%B0%E6%B3%A8%E5%86%8C%E7%9A%84%E5%9C%B0%E6%96%B9%EF%BC%8C%E8%AE%BF%E9%97%AE5173%E7%9A%84%E7%BD%91%E5%9D%80%E7%9B%B4%E6%8E%A5%E5%B0%B1%E6%98%AF%E7%99%BB%E5%BD%95%E9%A1%B5%E9%9D%A2)

他是配置了 pb 的后台端口号，默认就是8090，第一次打开会让你注册，后面登录就用你注册过的账号密码

**Comment by fangyu6** [comment]
恩 应该是的 但用pb的用户和密码登录不上情报分析

**Comment by bigbrother666sh** [comment]
用户名密码记错了？可以遗忘，重新设置
（记得更新.env)

**Comment by fangyu6** [comment]
pb可以正常登录，应该不是密码错误问题。如何重置密码？还有另个问题想请教下您，图片中的错误该如何解决？
![b7e9d79663e6e332d196957a439bf86](https://github.com/user-attachments/assets/1f18123a-69b9-4658-92d1-6ca2ad202e42)

**Comment by fangyu6** [comment]
pb可以正常登录，应该不是密码错误问题。如何重置密码？还有另个问题想请教下您，图片中的错误我该如何解决
![526cb25b2bd5be069a41823a123b993](https://github.com/user-attachments/assets/38ffba06-db84-47d7-99e1-9c74af3b3d7c)

**Comment by bigbrother666sh** [comment]
你模型名称写错了，然后你好像也没有配置 llm 服务的 key 等信息，建议再仔细读一下 readme

**Comment by fangyu6** [comment]
好的 我再配置下

**Comment by yichaosun** [comment]
ui/api上没有手动触发采集功能。事实上，我重启了container，也没有触发采集。
site：https://news.163.com/
tag：上海初中升学信息
从日志上看没有触发采集，llm都是配置了，但是没有采集也就没有后续llm相关是否配置有问题的日志

**Comment by bigbrother666sh** [comment]
tag 有没有设定为 activated？

**Comment by bryan-ym** [comment]
部署好了，也按照使用说明配置了tags、sites等，但是app并没有去搜集信息，因为后台看到的任务运行时间很短
![image](https://github.com/user-attachments/assets/37a479b6-cb9b-4183-85d6-0d52ecb70493)
同时在siliconflow上对应的api key没有使用记录，再根据siliconflow的api说明使用curl验证，容器后台是可以调用siliconflow的服务的，如下图，那我的问题在哪里？我已经修改了env文件中的LLM_API_BASE为完整路径仍然无法使app工作，难道我要去看app的代码？5555
![image](https://github.com/user-attachments/assets/e4c16506-ecfa-43f1-aabb-08ad130174bd)
请大神解惑
