### ISSUE TITLE
LLM模型大部分时间都没有结果的

### ISSUE THREAD

**Issue by seasonpengmaersk** [TeamWiseFlow/wiseflow#66]
我用的是siliconflow

export GET_INFO_MODEL="THUDM/glm-4-9b-chat"
export REWRITE_MODEL="Qwen/Qwen2-7B-Instruct"
export HTML_PARSE_MODEL="01-ai/Yi-1.5-9B-Chat-16K" 

我也试过很多其他的模型， 基本上都出不了结果。 

core-1  |  [{'role': 'system', 'content': "Please carefully read the user-inputted news content and analyze it based on the provided list of categories:\n['China', 'Apple']\n\nIf the news contains any information related to the above categories, mark the type of information using the following format and provide a one-sentence summary containing only the time, location, who involved, and the event:\n<tag>Category Name</tag> One-sentence summary including only time, location, who, and event.\n\nIf the news includes multiple pieces of information, analyze each one separately and output them in a line-by-line format. If the news does not involve any of the listed categories, simply output: N/A.\nImportant guidelines to follow: 1) Adhere strictly to the original news content, do not provide information not contained in the original text; 2) For the same event, select only the most fitting tag, avoiding duplicate outputs; 3) Summarize using just one sentence, and limit it to time, location, who, and event only; 4) Strictly comply with the given output format."}, {'role': 'user', 'content': 'title: Yahoo Finance\n\ncontent: [from finance] SC 13G/A Schedule filed to report acquisition of beneficial ownership of 5% or more of a class of equity securities by passive investors and certain institutions\nFeb 14, 2023'}]
core-1  | 2024-08-16 10:08:45.443 | DEBUG    | llms.openai_wrapper:openai_llm:18 - model: THUDM/glm-4-9b-chat
core-1  | 2024-08-16 10:08:45.443 | DEBUG    | llms.openai_wrapper:openai_llm:19 - kwargs:
core-1  |  {'temperature': 0.1}
core-1  | 2024-08-16 10:08:46.337 | DEBUG    | llms.openai_wrapper:openai_llm:30 - result:
core-1  |  Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='\nN/A', refusal=None, role='assistant', function_call=None, tool_calls=None))
core-1  | 2024-08-16 10:08:46.338 | DEBUG    | llms.openai_wrapper:openai_llm:31 - usage:
core-1  |  CompletionUsage(completion_tokens=3, prompt_tokens=272, total_tokens=275)
core-1  | 2024-08-16 10:08:46.338 | INFO     | insights.get_info:get_info:71 - can not find info, llm result:
core-1  | 
core-1  | N/A

**Comment by bigbrother666sh** [comment]
那你要看看你设定的tag和你的信源之间的匹配程度了。
wiseflow设计目标之一就是过滤不必要的信息，仅从你上面截图来看，送入的网页信息 “ [from finance] SC 13G/A Schedule filed to report acquisition of beneficial ownership of 5% or more of a class of equity securities by passive investors and certain institutions\nFeb 14, 2023a" 确实不包含任何'China'或者 'Apple'的信息，模型输出N/A 是正确的。
