### ISSUE TITLE
conda部署时，tasks和backend报错，.env和已经配置并按照第一次启动pocketbase的流程进行过处理

### ISSUE THREAD

**Issue by AlLenNotFound** [TeamWiseFlow/wiseflow#69]
<img width="823" alt="image" src="https://github.com/user-attachments/assets/0b517a91-ae23-4b3c-b818-181ebeed8d06">

**Comment by AlLenNotFound** [comment]
<img width="254" alt="image" src="https://github.com/user-attachments/assets/595ec390-c0ad-4733-8e0a-25d6544c05d8">

**Comment by HKbool** [comment]
我也是这个问题

**Comment by HKbool** [comment]
![微信截图_20240821160218](https://github.com/user-attachments/assets/84d41be5-f3b8-4423-b64c-af6938d34c1c)

**Comment by AllSimilar** [comment]
admin_data要改，在utils/pb_api.py中                admin_data = self.client.admins.auth_with_password("你的注册账号", "你的密码")

**Comment by HKbool** [comment]
哪里的账号密码?

**Comment by HKbool** [comment]
![微信截图_20240821160218](https://github.com/user-attachments/assets/7fd2dde9-9662-414b-9c52-0e273dc2a841)
改了还是错误!

**Comment by lambdayin** [comment]
@HKbool 
我是自己重写了个邮箱和密码（密码用的纯英文）就可以了

**Comment by bigbrother666sh** [comment]
> 先在`https://127.0.0.1:8090`注册账号, 然后把注册的用户名和密码填写到`.env`文件的`PB_API_AUTH`条目下.

https://127.0.0.1:8090/_/

**Comment by HKbool** [comment]
我使用的是docker compose up   进行的, 不是本地运行py

**Comment by HKbool** [comment]
我在 siliconflow.cn  已经申请了key 填写了

**Comment by bigbrother666sh** [comment]
看下 #47
