### ISSUE TITLE
关于修改日志级别

### ISSUE THREAD

**Issue by log2cn** [TeamWiseFlow/wiseflow#72]
`.env`中的`WS_LOG`条目只能控制日志文件`wiseflow.log`的级别, 不影响控制台输出.

为修改控制台输出日志级别, 可设置环境变量[`LOGURU_LEVEL=WARNING`](https://github.com/Delgan/loguru/issues/121).

**Comment by l0g2** [comment]
二者可以分别决定控制台和日志文件输出, 互不影响.
