### ISSUE TITLE
已正常使用但收集的信息与tag关联度很低

### ISSUE THREAD

**Issue by jiangfangcheung** [TeamWiseFlow/wiseflow#75]
已正常使用但收集的信息与tag关联度很低，麻烦帮忙看看是什么问题导致的？列表里面的tag是空值
![image](https://github.com/user-attachments/assets/6f1a16f9-b73a-4384-a119-68445aaefdd7)
![image](https://github.com/user-attachments/assets/74441fe9-6371-4a7d-bf10-c6b105661cda)
![image](https://github.com/user-attachments/assets/c6413300-987f-4c0b-8874-06168a372071)

**Comment by jiangfangcheung** [comment]
![image](https://github.com/user-attachments/assets/080649f9-35b0-4ca4-92f8-d1568432e4b0)

**Comment by l0g2** [comment]
article里面是全部文章, 其中与你的tag有关的部分在insights.

**Comment by jiangfangcheung** [comment]
但是insights里面是空的呢
![image](https://github.com/user-attachments/assets/dc703b75-03ea-41d5-af56-ff3256efe41f)

**Comment by l0g2** [comment]
> 但是insights里面是空的呢 ![image](https://private-user-images.githubusercontent.com/18694577/360817418-dc703b75-03ea-41d5-af56-ff3256efe41f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTM1NTIsIm5iZiI6MTcyNDQxMzI1MiwicGF0aCI6Ii8xODY5NDU3Ny8zNjA4MTc0MTgtZGM3MDNiNzUtMDNlYS00MWQ1LWFmNTYtZmYzMjU2ZWZlNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDExNDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzlhOWE4ZWExY2UzZjZjNTgyZmI1Zjk0NGUxNWYzZjYyMmFmZGNjNTNkOGQ4YWExMjM2MWJmYmI1ZTJlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chCFuWDxqNhy8rNsdpFTngcuNxHH-FudYndo49Rj5Fo)

就是没有识别到tag相关的。可能因为识别比较严格，你试试多加几个tag，或者把tag改宽松一些，或者多加几个网站，再多等一会儿。

**Comment by bigbrother666sh** [comment]
另外 tag设置为 activate状态了么……

**Comment by FunnyGiraffe** [comment]
这个需要设置openai的api_key么？docker compose up 后出现了错误 openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable，这个错误需要怎么解决

**Comment by jiangfangcheung** [comment]
> 另外 tag设置为 activate状态了么……

Tag都是active状态的，我多设置几个宽松的tag试一下
另外我是本地部署的大模型服务，KEY设置的是LM-Studio指定的，大模型有正常处理请求
