### ISSUE TITLE
项目已使用docker 启动   配置sites 如何生产数据

### ISSUE THREAD

**Issue by HKbool** [TeamWiseFlow/wiseflow#77]
如何生产数据  查询数据?
版本0.3.0

![微信截图_20240827165646](https://github.com/user-attachments/assets/169ab664-9289-4f5c-b399-021fcd3d639a)

**Comment by ccxxiicc** [comment]
请问你的sites、articles之类的是自己创建的吗？

**Comment by HKbool** [comment]
不是,网上抓取的

**Comment by HKbool** [comment]
我需要,怎么操作,可以搜索,生成报告什么的?

**Comment by ccxxiicc** [comment]
你是用哪种方式部署的？我尝试docker-compose up会报错，直接用docker pull bigbrother666sh/wiseflow:latest 出来的页面是这样的
![Uploading 微信截图_20240827172323.png…]()

**Comment by HKbool** [comment]
我使用 docker-compose up  搭建的

**Comment by ccxxiicc** [comment]
你在 docker-compose up的时候有遇到什么问题吗？我在Step 2/11 : RUN apt-get update &&     apt-get upgrade -y &&     apt-get install -y tzdata build-essential unzip &&    apt-get clean
的时候很不顺利

**Comment by HKbool** [comment]
docker-compose up  我没遇到问题

**Comment by ccxxiicc** [comment]
我重新操作成功了，你的问题现在得到解决办法了吗？

**Comment by bigbrother666sh** [comment]
> 如何生产数据 查询数据? 版本0.3.0
> 
> ![微信截图_20240827165646](https://private-user-images.githubusercontent.com/16604879/361730686-169ab664-9289-4f5c-b399-021fcd3d639a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjQ1NzQsIm5iZiI6MTcyNDc2NDI3NCwicGF0aCI6Ii8xNjYwNDg3OS8zNjE3MzA2ODYtMTY5YWI2NjQtOTI4OS00ZjVjLWIzOTktMDIxZmNkM2Q2MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEzMTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTYzOGExZDJlMzYwN2IyZTRlZjEzMGQ2NzE4Nzk0YTZlYjBkNTBkZDU2ZjA1N2YxNTA0MDI0Zjg2NzU4MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jlM3EjxGZdgLmi18QbgxbZogBHZRYPJsP7n7YTXqUl0)

填tags。
另外我看你填写的是微信的一个文章页面，这是文章列表页面吗？是的话，目前还不支持，但有人提了PR，你可以参考下 #55

**Comment by HKbool** [comment]
@bigbrother666sh  我需要怎么操作?才能搜索自己想要的数据

**Comment by ccxxiicc** [comment]
设置好sites和tag应该就行了
![微信截图_20240828102631](https://github.com/user-attachments/assets/26aef435-35b1-43f9-a902-35aaaf1ed2de)

**Comment by HKbool** [comment]
@ccxxiicc  我意思是设置好了,怎么查看想要的数据呢

**Comment by HKbool** [comment]
https://www.bilibili.com/video/BV17F4m1w7Ed/?spm_id_from=333.337.search-card.all.click&vd_source=80d83e555af2502a058382462f99c67b  @ccxxiicc

**Comment by ccxxiicc** [comment]
> https://www.bilibili.com/video/BV17F4m1w7Ed/?spm_id_from=333.337.search-card.all.click&vd_source=80d83e555af2502a058382462f99c67b

我也想知道这里的生成报告是怎么得到的 @bigbrother666sh

**Comment by bigbrother666sh** [comment]
生成报告是旧版本的功能，0.30版本已经调整取消。
但是Dashboard里面有参考代码，可以自己调整下 ，参考 #52 
欢迎调整后提PR

**Comment by Zzaa2020** [comment]
生成报告感觉是一个非常棒的功能,建议上线

**Comment by bryan-ym** [comment]
> 你在 docker-compose up的时候有遇到什么问题吗？我在Step 2/11 : RUN apt-get update && apt-get upgrade -y && apt-get install -y tzdata build-essential unzip && apt-get clean 的时候很不顺利

你在Dockerfile这个文件中，找到你上面那句话，在它前面加上这段代码：
RUN sed -i 's|deb.debian.org|mirrors.aliyun.com|g' /etc/apt/sources.list.d/debian.sources
重新运行docker compose up
