### ISSUE TITLE
conda直接部署后，出现连接数据库问题

### ISSUE THREAD

**Issue by 989829889** [TeamWiseFlow/wiseflow#80]
按照上述步骤conda直接部署后，出现连接数据库问题
![8e0c737e98426d7c3594c0f208e220f](https://github.com/user-attachments/assets/7bf4648a-86ed-464f-b34c-f0bbb06f266d)
sites，tags集合均已创建，不知道问题所在

**Comment by bigbrother666sh** [comment]
设置 activated 了么？

**Comment by wl826214** [comment]
> 设置 activated 了么？

怎么设置？

**Comment by bigbrother666sh** [comment]
http://127.0.0.1:8090/_/   tag页面
