### ISSUE TITLE
insight部分

### ISSUE THREAD

**Issue by ccxxiicc** [TeamWiseFlow/wiseflow#82]
使用siliconflow，已经填写了apikey之类的，但是一直有这样的连接错误，爬取文章是正常的，但是不能生成insight
![微信截图_20240828224339](https://github.com/user-attachments/assets/3295070d-348f-4abf-96f5-b4ea6527c2e2)
改用ollama后还是在这报错
![微信截图_20240828220912](https://github.com/user-attachments/assets/a79785e5-58ef-44fb-bef5-d33f493225ed)

**Comment by bigbrother666sh** [comment]
如果你使用 siliconflow_wrapper的话就不要配置LLM_API_BASE了
