### ISSUE TITLE
结果都是乱码，    environment:       - TZ=Asia/Shanghai       - LANG=zh_CN.UTF-8       - LC_ALL=zh_CN.UTF-8以及启用了，还有就是能更新dashboard吗

### ISSUE THREAD

**Issue by xs818818** [TeamWiseFlow/wiseflow#83]
![2024-08-29 12-52-24屏幕截图](https://github.com/user-attachments/assets/1f0afb82-9a3a-40c3-bf2a-ba55ba333036)

**Comment by 989829889** [comment]
我想请问一下，这个articles是自己配置出来的吗？开启了task.py成功登录了pocketbase但是为什么会连接不上sites和tags，这个都按教程配置的TT

**Comment by bigbrother666sh** [comment]
> ![2024-08-29 12-52-24屏幕截图](https://private-user-images.githubusercontent.com/4013338/362536517-1f0afb82-9a3a-40c3-bf2a-ba55ba333036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDE2ODMsIm5iZiI6MTcyNTI0MTM4MywicGF0aCI6Ii80MDEzMzM4LzM2MjUzNjUxNy0xZjBhZmI4Mi05YTNhLTQwYzMtYmYyYS1iYTU1YmEzMzMwMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDE0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg5NjNjZDExZDhkYzdiMmNmMWVkMDA4ZGUxMmM3YTYyZmU2MDM4NzFhZDBhOGFmMTY4ZjAwZjI1YTA1NjYzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bs9yEfU9uOsaZlo4GeUjqIe_1t008-iWX5A5eBDrEMk)

部分国内网站用的编码不规范，是会出现这个情况，可以仿照general_scraper写一下专有解析器

**Comment by bigbrother666sh** [comment]
> 我想请问一下，这个articles是自己配置出来的吗？开启了task.py成功登录了pocketbase但是为什么会连接不上sites和tags，这个都按教程配置的TT

sites和tags要在http://127.0.0.1:8090/_/ 中的sites和tags界面配置
