### ISSUE TITLE
Tags 设置了 但是抓取出来的信息都是跟Tag无关的

### ISSUE THREAD

**Issue by fengjiahang999** [TeamWiseFlow/wiseflow#84]
Tags 设置了 但是抓取出来的信息都是跟Tag无关的，我设置的是NBA库里，想搜索到NBA库里的相关信息，但是出来的都不是！！！

是哪些地方设置的不对么？希望源主给予解答！！！

**Comment by bigbrother666sh** [comment]
提取的信息在  info里面，不在 article里面
