### ISSUE TITLE
如何通过API获取到已抓取的信息

### ISSUE THREAD

**Issue by airyyan** [TeamWiseFlow/wiseflow#87]
articles列表里有很多数据，但是通过api调用查询时返回没有数据：
![image](https://github.com/user-attachments/assets/9631a077-3369-4e1d-bca6-43163fa83402)
![image](https://github.com/user-attachments/assets/79038a07-e3eb-4df5-92f4-48262f9a8492)

**Comment by bigbrother666sh** [comment]
提取已获得的数据，无关wiseflow，可以直接针对pocketbase进行操作，参考
https://github.com/vaphes/pocketbase
或者
https://pocketbase.io/docs/
