### ISSUE TITLE
articles可以获取到网站列表页中的部分数据，但是tags太多，始终获取不准想要的数据，insights里面也是空，我该怎样完善？

### ISSUE THREAD

**Issue by Nero-Prime** [TeamWiseFlow/wiseflow#89]
比如供应商来源:
二、供应商来源
邀请供应商的情况
1、供应商产生方式：（√）公告邀请 （ ）供应商库抽取 （ ）采购人、专家推荐
这是正确的信息。还有很多没获取到

**Comment by Nero-Prime** [comment]
![Uploading b9c60acb2858b67bbc82b7b368d9225.png…]()

**Comment by Nero-Prime** [comment]
<img width="815" alt="b9c60acb2858b67bbc82b7b368d9225" src="https://github.com/user-attachments/assets/a07677c0-edbc-4c56-aed8-de0ca38a6986">

**Comment by Nero-Prime** [comment]
还有就是我每次启动tasks只能获取到一条链接

**Comment by bigbrother666sh** [comment]
看起来你的信源比较特殊，建议针对常用的信源编写专有信源信息提取器，可以参考：core/scrapers/README_CN.md
