### ISSUE TITLE
可以增加爬取微博、小红书、知乎的功能吗

### ISSUE THREAD

**Issue by dengdylan8** [TeamWiseFlow/wiseflow#90]

**Comment by bigbrother666sh** [comment]
计划中……

**Comment by wrzszhaowei** [comment]
微博，小红书，知乎真的是太需要了。
希望官网尽快完善哈，感谢感谢。

**Comment by bigbrother666sh** [comment]
你们都是要做什么场景，对社媒信息的获取这么迫切？

**Comment by wrzszhaowei** [comment]
> 你们都是要做什么场景，对社媒信息的获取这么迫切？

您好，我其实是想根据tags搜索各个平台比较热门的文章。但这些社媒平台现在不登录都访问不了（例如知乎），这部分怎么操作呢？
公众号现在也是只能一篇文章一篇文章的获取吗？能根据某一个账号获取其他所有文章呢？

**Comment by bigbrother666sh** [comment]
V0.3.8版本会尽量提供这方面的支持
