### ISSUE TITLE
简报发送到微信群怎么设置呢？微信群没有id

### ISSUE THREAD

**Issue by dengdylan8** [TeamWiseFlow/wiseflow#92]

**Comment by bigbrother666sh** [comment]
参考 https://github.com/TeamWiseFlow/awada

**Comment by dengdylan8** [comment]
![image](https://github.com/user-attachments/assets/896fade7-4076-480c-b5de-3b5f60de86ea)
群聊的ID：49591466778 这个是怎么获取的

**Comment by bigbrother666sh** [comment]
你先跑通wxbot和dm.py,  然后在目标群里说句话，就能看到了
