### ISSUE TITLE
爬取出来的文章，只是对单篇文章的提炼，能否做到对多篇具有相同tag的文章，进行总结提炼，推送的时候附多个相关的URL

### ISSUE THREAD

**Issue by dengdylan8** [TeamWiseFlow/wiseflow#94]
目前效果如下：
智慧港口
[from 智能交通技术] 防城港市制定国际现代物流中心专项规划，旨在打造辐射西部、面向全国、对接东盟的国际现代物流中心，预计至2030年形成具有国际影响力的现代物流中心。
https://mp.weixin.qq.com/s?__biz=MzI5NzExMTY0Mg==&mid=2650805744&idx=1&sn=32a034137d26a49275c27fb929172ddc
[from 中国港口] 8月29日，国家能源集团天津港务科技成果“煤炭港口全流程智能管控关键技术研究及应用”达到国际领先水平。
https://mp.weixin.qq.com/s?__biz=Mzg5ODcwNDE5OA==&mid=2247573667&idx=2&sn=37e8d5a817c669d37ce009e08542e845
[from 上海航运交易所] 2020年11月5日，广州海关创新推出“一港通”模式，实现进出口货物“一次申报、一次查验、一次放行”。
https://mp.weixin.qq.com/s?__biz=MzIyMzU5MDg1MQ==&mid=2247515189&idx=1&sn=fd162078431ba600be77eb3f6469881c
[from 上海航运交易所] 8月21日，台州南铁路物流基地项目圆满完成拨接施工，顺利保障杭深线、金台线按时恢复正常运行，是国家二级3.0版本的铁路智慧物流基地。
https://mp.weixin.qq.com/s?__biz=MzIyMzU5MDg1MQ==&mid=2247515189&idx=2&sn=e9c148a79cb5667430be57b30cc5cc6f
[from 北部湾港集团] 钦州港依托国际贸易“单一窗口”，通过实施口岸作业流程再造和无纸化信息建设，整合建设“数智化”港口综合服务平台，创新实现铁海联运港站“一体化”智能监测“秒通关”，提升集装箱“数智化”治理能力。
https://mp.weixin.qq.com/s?__biz=MzA4MzE1ODE0Nw==&mid=2650632203&idx=2&sn=fd0c5209c217c5b977be7776c0fe518a

期望的效果：
tag
[from 公众号] 提炼讯息1 提炼讯息2 提炼讯息3
https://mp.weixin.qq.com/url1
https://mp.weixin.qq.com/url2
https://mp.weixin.qq.com/url3

**Comment by bigbrother666sh** [comment]
这个在awada 的task.py重写下 简讯的拼接方式不就行了。

wiseflow本身是不支持跨文章提取的，不过支持对提取到的近似info进行自动合并，如果需要调整近似度参数，可以更改 core/insights/__init__.py 86行的入参，值越高越不敏感
