### ISSUE TITLE
第一次用docker，我按照作者的步骤，运行了docker compose up之后，那几条url无法进入，报错404.换成本地地址也是不行？希望有人能为我解答，我非常感谢

### ISSUE THREAD

**Issue by mlgbcao666** [TeamWiseFlow/wiseflow#95]
![image](https://github.com/user-attachments/assets/3ef0ebc8-13d2-46bd-8141-e6f1c0b46fee)

**Comment by bigbrother666sh** [comment]
这不是已经执行了？只是日期太旧，舍弃了。默认是抓取三天内的信息，可以更改core/insights/__init__.py中的expiration_days更改
