### ISSUE TITLE
汽车之家论坛只有头尾信息

### ISSUE THREAD

**Issue by Robin021** [TeamWiseFlow/wiseflow#96]
<img width="679" alt="image" src="https://github.com/user-attachments/assets/e739137d-6094-49dd-ab37-1fe3966945e4">
测试地址
https://club.autohome.com.cn/bbs/forum-c-7036-1.html

**Comment by bigbrother666sh** [comment]
可能要写专有解析器了，或者等十月中旬下一个版本会升级目前的通用解析器

**Comment by bigbrother666sh** [comment]
哥们看了下，你这个是论坛啊……
