### ISSUE TITLE
awada推送的消息有大量重复数据怎么处理呢？

### ISSUE THREAD

**Issue by dengdylan8** [TeamWiseFlow/wiseflow#97]
![image](https://github.com/user-attachments/assets/5eb648e2-f5e0-49c6-9aea-b51485c04cca)
另外：启动wiseflow的时候设置了时区，没有生效呢？显示的不是北京时间

**Comment by bigbrother666sh** [comment]
core/insights/__init__.py  83行入参调低，0.65改为0.5试试
